"""Baseline of request-body fields still missing an upper bound (stage 17, QA run 01).

This set only SHRINKS. Every later stage-17 task that bounds a field deletes
that field's key here in the same commit, in the module it owns; Task 8
deletes this file once the set is empty. Do not add a key that was never
here — a newly introduced unbounded field is a regression
`tests/test_request_bounds.py` must catch, not a baseline entry to grow.

Measured 2026-09-24 against branch base c307922 (stage 16 merged): 474
request-body fields checked, 201 without a bound. The stage's own research
walk (a throwaway script, same idea as the convention test) counted 224
before stage 16 merged; stage 16 added some request schemas and also
bounded some fields the walk had flagged, so the two counts are not
expected to match exactly.
"""

BASELINE: frozenset[str] = frozenset(
    {
        "ActCreateIn.answers",
        "ActCreateIn.facts",
        "ActCreateIn.gps_accuracy_m",
        "ActCreateIn.notes",
        "ActFileIn.device",
        "ActSignIn.pkcs7",
        "ActUpdateIn.answers",
        "ActUpdateIn.facts",
        "ActUpdateIn.gps_accuracy_m",
        "ActUpdateIn.notes",
        "ActivityTypePatch.processing_days",
        "ActivityTypePatch.sort_order",
        "AnnouncementCreateIn.file_ids",
        "AnnouncementPatchIn.file_ids",
        "AppealResolveIn.result",
        "ApplicationApproveIn.pkcs7",
        "ApplicationConclusionIn.text",
        "ApplicationDocumentIn.note",
        "ApplicationFileIn.documents",
        "ApplicationFileIn.items",
        "ApplicationFileIn.pkcs7",
        "ApplicationFileIn.quantity",
        "ApplicationFilingIn.documents",
        "ApplicationFilingIn.items",
        "ApplicationFilingIn.quantity",
        "ApplicationPatch.items",
        "ApplicationPatch.quantity",
        "ApplicationRejectIn.pkcs7",
        "ApplicationRequestInfoIn.message",
        "ApplicationRespondInfoIn.file_ids",
        "ApplicationRespondInfoIn.text",
        "ApplicationReturnIn.fields_to_fix",
        "ApplicationSubmitIn.pkcs7",
        "AudienceIn.region_ids",
        "AudienceIn.role_codes",
        "AudienceIn.role_codes[]",
        "BeekeeperCreateIn.certificate_no",
        "BeekeeperCreateIn.farm_name",
        "BeekeeperCreateIn.full_name",
        "BeekeeperCreateIn.passport_number",
        "BeekeeperCreateIn.passport_series",
        "BeekeeperPatchIn.certificate_no",
        "BeekeeperPatchIn.farm_name",
        "BeekeeperPatchIn.full_name",
        "BeekeeperPatchIn.passport_number",
        "BeekeeperPatchIn.passport_series",
        "Body_create_bank_statement_api_v1_payments_bank_statements_post.column_map",
        "Body_create_bank_statement_api_v1_payments_bank_statements_post.file",
        "Body_create_import_api_v1_gis_imports_post.attributes",
        "Body_create_import_api_v1_gis_imports_post.file",
        "Body_create_import_api_v1_gis_imports_post.format",
        "Body_create_import_api_v1_gis_imports_post.layer_code",
        "Body_upload_file_api_v1_files_post.file",
        "ChecklistIn.code",
        "ChecklistIn.items",
        "ChecklistQuestion.code",
        "ClassifierIn.code",
        "ClassifierItemIn.code",
        "ClassifierItemIn.props",
        "ClassifierItemIn.sort_order",
        "ClassifierItemPatch.props",
        "ClassifierItemPatch.sort_order",
        "ContourIn.number",
        "ExplanationIn.text",
        "FeatureIn.geom",
        "FeatureIn.props",
        "FeaturePatch.props",
        "LayerPatch.style",
        "LegalDocumentCreateIn.doc_number",
        "LegalDocumentCreateIn.sort_order",
        "LegalDocumentCreateIn.source_url",
        "LegalDocumentPatchIn.doc_number",
        "LegalDocumentPatchIn.sort_order",
        "LegalDocumentPatchIn.source_url",
        "OrganizationIn.code",
        "OrganizationIn.kind",
        "OrganizationIn.requisites",
        "OrganizationPatch.requisites",
        "PermissionCodesIn.codes",
        "PermissionCodesIn.codes[]",
        "ReportDataUpdate.rows",
        "ReportDataUpdate.rows[]",
        "ReportFormColumn.code",
        "ReportFormCreate.columns",
        "ReportFormCreate.rules",
        "ReportFormCreate.rules[]",
        "ReportFormCreate.schedule",
        "ReportFormCreate.version",
        "ReportSignIn.pkcs7",
        "RoleCreateIn.code",
        "RoleCreateIn.copy_from",
        "RoleCreateIn.max_approve_amount",
        "RoleCreateIn.max_approve_area",
        "RolePatchIn.max_approve_amount",
        "RolePatchIn.max_approve_area",
        "SplitIn.accuracy_m",
        "SplitPieceIn.declared_area_ha",
        "SplitPieceIn.geom",
        "SplitPieceIn.number",
        "UserBlockIn.reason",
        "UserCreateIn.email",
        "UserCreateIn.full_name",
        "UserCreateIn.login",
        "UserCreateIn.phone",
        "UserCreateIn.position",
        "UserCreateIn.role_code",
        "UserPatchIn.email",
        "UserPatchIn.full_name",
        "UserPatchIn.login",
        "UserPatchIn.phone",
        "UserPatchIn.position",
        "UserPatchIn.role_code",
        "VersionIn.accuracy_m",
        "VersionIn.declared_area_ha",
        "VersionIn.geom",
        "VersionPatch.accuracy_m",
        "VersionPatch.declared_area_ha",
        "app__modules__inspections__schemas__AppealIn.text",
        "app__modules__inspections__schemas__DecisionIn.damage_amount",
        "app__modules__inspections__schemas__DecisionIn.damage_calc",
        "app__modules__inspections__schemas__DecisionIn.note",
    }
)
