"""The Payme JSON-RPC server (design/04 §3, plan `03.10a-payments-core` task 4).

Every test drives the route over HTTP (`client`, an anonymous Basic-Auth
client — `conftest.py`) rather than calling `payme.handle` directly: the
always-200 guarantee is a property of `payme_router.py`, not of `payme.py`
alone, and only an HTTP round-trip can prove it.

Two tests are restructured from the brief per ruling F — see each one's own
docstring for why. One assertion is restructured beyond ruling F, in
`test_perform_marks_the_invoice_paid_writes_the_ledger_and_moves_the_application`
— see its own docstring: `applications` ships no `router.py` on this branch
(verified: no `app/modules/applications/router.py`, no route anywhere
matching `applications/{`), so the brief's own
`GET /api/v1/applications/{id}` call would 404 regardless of this task's
correctness. The invariant it was checking (the application reached PAID)
is instead verified by reading the row back through
`applications.service.get`, the same public surface `payments.service`
itself uses.

Every Payme transaction `id` used below is generated by `_tx_id()`, never a
fixed literal (lesson: "The test DB is shared, persistent, and never empty"):
`client` is `_commit_pending_before_requests`-based and commits every request
for real, so a fixed literal like `"payme-tx-1"` would collide with the SAME
test's own row from a previous run (or a sibling worktree's), silently
changing what `CreateTransaction`'s idempotent-replay branch sees — a stale
row from hours or days ago reads as "past the 12h timeout" against the real
current time. Two count/total assertions are scoped to the row(s) this test
itself created for the identical reason: an unscoped `count(*)` over
`provider_transactions`/`allocations` counts every OTHER test's committed
rows too.
"""

import base64
import uuid
from datetime import timedelta
from decimal import Decimal

import pytest


def _tx_id(label: str) -> str:
    """A Payme transaction id unique to this test run — see the module
    docstring for why a fixed literal is unsafe against the shared,
    persistent test DB."""
    return f"payme-{label}-{uuid.uuid4().hex[:12]}"


def _auth(key: str = "test-cashbox-key") -> dict[str, str]:
    token = base64.b64encode(f"Paycom:{key}".encode()).decode()
    return {"Authorization": f"Basic {token}"}


async def _rpc(client, method: str, params: dict, *, key: str = "test-cashbox-key"):
    return await client.post(
        "/api/v1/webhooks/payme",
        json={"jsonrpc": "2.0", "id": 1, "method": method, "params": params},
        headers=_auth(key),
    )


async def test_every_answer_is_http_200_including_the_errors(client, pending_invoice):
    """Ruling 2 / design/04 §3.1: Payme reads a non-200 as -32400, so even bad
    credentials and unknown methods must come back 200 with the error in the body."""
    bad_key = await _rpc(client, "CheckTransaction", {"id": "x"}, key="wrong")
    assert bad_key.status_code == 200
    assert bad_key.json()["error"]["code"] == -32504

    unknown = await _rpc(client, "NoSuchMethod", {})
    assert unknown.status_code == 200
    assert unknown.json()["error"]["code"] == -32601


async def test_a_malformed_body_never_500s(client):
    """Ruling B: malformed JSON and a non-object RPC envelope both answer 200
    with a Payme error code, never FastAPI's own `RequestValidationError` 422
    or an unhandled 500 — this route is never typed by a pydantic model."""
    garbage = await client.post("/api/v1/webhooks/payme", content=b"{not json", headers=_auth())
    assert garbage.status_code == 200
    assert garbage.json()["error"]["code"] == -32700

    not_an_object = await client.post("/api/v1/webhooks/payme", json=[1, 2, 3], headers=_auth())
    assert not_an_object.status_code == 200
    assert not_an_object.json()["error"]["code"] == -32600

    no_method = await client.post(
        "/api/v1/webhooks/payme", json={"jsonrpc": "2.0", "id": 1, "params": {}}, headers=_auth()
    )
    assert no_method.status_code == 200
    assert no_method.json()["error"]["code"] == -32600


async def test_a_missing_authorization_header_answers_32504(client):
    """Ruling E: a missing/malformed header is -32504, never an exception —
    `hmac.compare_digest` must never even be reached with a `None`."""
    result = await client.post(
        "/api/v1/webhooks/payme",
        json={"jsonrpc": "2.0", "id": 1, "method": "CheckTransaction", "params": {"id": "x"}},
    )
    assert result.status_code == 200
    assert result.json()["error"]["code"] == -32504


async def test_a_commit_failure_never_escapes_as_a_500(db, client, pending_invoice, monkeypatch):
    """Review finding I1: `payme_router._process`'s own `db.commit()` calls
    can themselves raise (a genuine DB-level failure at exactly that
    moment) — `payme_rpc`'s outer guard must still answer 200 `-32400`,
    never let it escape past `get_db` into `app.main`'s generic 500.

    Patches `AsyncSession.commit` to raise on its FIRST call against any
    session OTHER than this test's own `db` fixture — `db` must keep
    committing normally throughout, or `_commit_pending_before_requests`'s
    own pre-request commit (needed for `pending_invoice` to be visible to
    the app's separate connection at all) would itself trip this same
    patch. The APP's per-request session's first commit, for a plain
    `CheckPerformTransaction` call, is `_process`'s own success-path one —
    exactly one of the three sites review finding I1 named."""
    from sqlalchemy.ext.asyncio import AsyncSession

    real_commit = AsyncSession.commit
    tripped = {"done": False}

    async def _flaky_commit(self: AsyncSession) -> None:
        if self is not db and not tripped["done"]:
            tripped["done"] = True
            raise RuntimeError("simulated commit failure")
        await real_commit(self)

    monkeypatch.setattr(AsyncSession, "commit", _flaky_commit)

    result = await _rpc(
        client,
        "CheckPerformTransaction",
        {"amount": int(pending_invoice.amount * 100), "account": {"id": pending_invoice.number}},
    )
    assert result.status_code == 200
    assert result.json()["error"]["code"] == -32400
    assert tripped["done"] is True  # the patch actually fired — not a vacuous pass


async def test_check_perform_rejects_a_wrong_amount(client, pending_invoice):
    result = await _rpc(
        client, "CheckPerformTransaction", {"amount": 1, "account": {"id": pending_invoice.number}}
    )
    assert result.json()["error"]["code"] == -31001


async def test_check_perform_accepts_a_correct_amount(client, pending_invoice):
    result = await _rpc(
        client,
        "CheckPerformTransaction",
        {
            "amount": int(pending_invoice.amount * 100),
            "account": {"id": pending_invoice.number},
        },
    )
    assert result.json()["result"] == {"allow": True}


async def test_check_perform_rejects_an_unknown_invoice(client):
    result = await _rpc(
        client,
        "CheckPerformTransaction",
        {"amount": 10_000_000, "account": {"id": "INV-2027-999999"}},
    )
    assert -31099 <= result.json()["error"]["code"] <= -31050


async def test_create_transaction_is_idempotent_by_paymes_id(db, client, pending_invoice):
    """Ruling 5 / design/04 §3.9: when Payme loses our answer it repeats the call
    verbatim. A second transaction row here would double-charge the applicant."""
    from sqlalchemy import func, select

    from app.modules.payments.models import ProviderTransaction

    tx_id = _tx_id("idempotent")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    first = await _rpc(client, "CreateTransaction", params)
    second = await _rpc(client, "CreateTransaction", params)

    assert first.json()["result"]["transaction"] == second.json()["result"]["transaction"]
    assert first.json()["result"]["state"] == second.json()["result"]["state"] == 1
    assert first.json()["result"]["create_time"] == second.json()["result"]["create_time"]
    count = await db.scalar(
        select(func.count())
        .select_from(ProviderTransaction)
        .where(ProviderTransaction.provider == "payme", ProviderTransaction.external_id == tx_id)
    )
    assert count == 1


async def test_perform_marks_the_invoice_paid_writes_the_ledger_and_moves_the_application(
    db, client, pending_invoice
):
    """The single most important test in this stage: money arrives, and every
    consequence of that lands in one transaction.

    The brief's own version additionally asserted the application's card via
    `GET /api/v1/applications/{id}` through an unrelated `applicant_client`.
    `applications` ships no `router.py` on this branch (3.9a branch 1 only —
    verified, no route anywhere matches `applications/{`), so that call would
    404 regardless of this task's own correctness, and the 404's error
    envelope carries no `status` key either. The same invariant — the
    application reached PAID — is instead verified by reading the row back
    through `applications.service.get`, the public surface `payments.service`
    itself uses; `applicant_client` is dropped since nothing else in this
    test needs it.
    """
    from sqlalchemy import select

    from app.modules.applications import service as applications_service
    from app.modules.payments.models import Allocation

    params = {
        "id": _tx_id("perform"),
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)
    performed = await _rpc(client, "PerformTransaction", {"id": params["id"]})

    assert performed.json()["result"]["state"] == 2
    await db.refresh(pending_invoice)
    assert pending_invoice.status == "paid"
    assert pending_invoice.paid_at is not None

    entries = (
        await db.scalars(select(Allocation).where(Allocation.invoice_id == pending_invoice.id))
    ).all()
    # Stage 7.9 task 5: the seeded `budget_50` directory row (migration
    # `0045`) is now a configured RECEIVER, not the old engine's fixed
    # "budget" half.
    assert {e.target for e in entries} == {"recipient", "receiver"}
    assert sum(e.amount for e in entries) == pending_invoice.amount

    application = await applications_service.get(db, pending_invoice.application_id)
    assert application is not None
    await db.refresh(application)
    assert application.status == "PAID"


async def test_perform_is_idempotent_and_does_not_double_the_ledger(db, client, pending_invoice):
    from sqlalchemy import func, select

    from app.modules.payments.models import Allocation

    params = {
        "id": _tx_id("perform-idempotent"),
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)
    first = await _rpc(client, "PerformTransaction", {"id": params["id"]})
    second = await _rpc(client, "PerformTransaction", {"id": params["id"]})

    assert first.json()["result"]["perform_time"] == second.json()["result"]["perform_time"]
    count = await db.scalar(
        select(func.count())
        .select_from(Allocation)
        .where(Allocation.invoice_id == pending_invoice.id)
    )
    assert count == 2


async def test_performing_against_a_cancelled_invoice_answers_31008(db, client, pending_invoice):
    """Ruling F (restructured — the brief's own version cannot work as written:
    CreateTransaction against an ALREADY-cancelled invoice never creates a
    transaction row at all, so a PerformTransaction against that same id is
    -31003 'not found', never -31008).

    The real race this rule protects against: create the transaction while
    the invoice is still pending, THEN cancel the invoice (publishing
    `applications.events.APPLICATION_CANCELLED`, which
    `payments.subscribers.on_application_cancelled` turns into a cancelled
    invoice — the applicant withdrew between CreateTransaction and now), THEN
    PerformTransaction — which must answer 'cannot perform' rather than
    forcing an illegal CANCELLED -> PAID application transition inside a
    route that must always answer 200."""
    from app.core.events import Event, publish
    from app.modules.applications.events import APPLICATION_CANCELLED

    tx_id = _tx_id("cancel-race")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    created = await _rpc(client, "CreateTransaction", params)
    assert created.json()["result"]["state"] == 1

    await publish(
        db,
        Event(
            name=APPLICATION_CANCELLED, payload={"application_id": pending_invoice.application_id}
        ),
    )
    await db.commit()
    await db.refresh(pending_invoice)
    assert pending_invoice.status == "cancelled"

    performed = await _rpc(client, "PerformTransaction", {"id": tx_id})
    assert performed.status_code == 200
    assert performed.json()["error"]["code"] == -31008


async def test_creating_a_transaction_against_a_cancelled_invoice_is_refused(
    client, cancelled_invoice
):
    """Ruling F's second half, corrected by whole-branch review finding I2
    (my ruling F was too narrow, not the reviewer's instinct — see
    `payme.py`'s own module docstring): `CreateTransaction` against an
    invoice that is ALREADY cancelled (never one this call itself just
    raced against) is `-31008` ("cannot perform"), because
    `CheckPerformTransaction`/`CreateTransaction` share one check and a
    FOUND-but-not-`pending` invoice is a "cannot perform" answer, not an
    "unknown account" one — telling a citizen whose invoice is already
    settled that the ACCOUNT NUMBER is wrong would send them back to
    re-enter a number that was never the problem. The plan's own original
    text already accepted either code here (`in (-31008, -31050)`), so this
    is inside the plan, not a deviation from it."""
    result = await _rpc(
        client,
        "CreateTransaction",
        {
            "id": _tx_id("precancelled"),
            "time": 1_800_000_000_000,
            "amount": int(cancelled_invoice.amount * 100),
            "account": {"id": cancelled_invoice.number},
        },
    )
    assert result.json()["error"]["code"] == -31008


async def test_creating_a_transaction_against_an_unknown_invoice_is_an_account_error(client):
    """The other half of finding I2's split: an invoice number that resolves
    to NOTHING is still `-31050…-31099` from `CreateTransaction`, exactly as
    it already is from `CheckPerformTransaction` — only "found but not
    payable" moved to `-31008`, "not found at all" did not."""
    result = await _rpc(
        client,
        "CreateTransaction",
        {
            "id": _tx_id("unknown-account"),
            "time": 1_800_000_000_000,
            "amount": 10_000_000,
            "account": {"id": "INV-2027-999999"},
        },
    )
    assert -31099 <= result.json()["error"]["code"] <= -31050


async def test_a_transaction_older_than_twelve_hours_is_cancelled_with_reason_four(
    db, client, pending_invoice, frozen_clock
):
    """Ruling 4 / design/04 §3.4: 43 200 000 ms from our create_time, cancelled
    by us with reason 4, and PerformTransaction then answers -31008."""
    tx_id = _tx_id("timeout-perform")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)

    frozen_clock.advance(timedelta(hours=12, minutes=1))
    performed = await _rpc(client, "PerformTransaction", {"id": tx_id})
    assert performed.json()["error"]["code"] == -31008

    checked = await _rpc(client, "CheckTransaction", {"id": tx_id})
    assert checked.json()["result"]["state"] == -1
    assert checked.json()["result"]["reason"] == 4


async def test_a_transaction_created_after_the_timeout_replays_cancelled(
    db, client, pending_invoice, frozen_clock
):
    """The OTHER half of ruling 4: `CreateTransaction` itself, not just
    `PerformTransaction`, must cancel-and-refuse a replay of an id whose
    original attempt is already past the 12h window — Payme repeats
    `CreateTransaction` calls too (design/04 §3.9), not only `Perform`."""
    tx_id = _tx_id("timeout-create")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)

    frozen_clock.advance(timedelta(hours=12, minutes=1))
    replay = await _rpc(client, "CreateTransaction", params)
    assert replay.json()["error"]["code"] == -31008

    checked = await _rpc(client, "CheckTransaction", {"id": tx_id})
    assert checked.json()["result"]["state"] == -1
    assert checked.json()["result"]["reason"] == 4


async def test_cancelling_a_performed_transaction_gives_state_minus_two(
    db, client, pending_invoice
):
    tx_id = _tx_id("cancel-performed")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)
    await _rpc(client, "PerformTransaction", {"id": tx_id})

    cancelled = await _rpc(client, "CancelTransaction", {"id": tx_id, "reason": 5})
    assert cancelled.json()["result"]["state"] == -2

    checked = await _rpc(client, "CheckTransaction", {"id": tx_id})
    assert checked.json()["result"]["reason"] == 5
    assert checked.json()["result"]["cancel_time"] > 0


async def test_cancelling_a_created_transaction_gives_state_minus_one(client, pending_invoice):
    tx_id = _tx_id("cancel-created")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)

    cancelled = await _rpc(client, "CancelTransaction", {"id": tx_id, "reason": 1})
    assert cancelled.json()["result"]["state"] == -1


async def test_cancel_transaction_unknown_id_answers_31003(client):
    result = await _rpc(client, "CancelTransaction", {"id": _tx_id("unknown"), "reason": 1})
    assert result.json()["error"]["code"] == -31003


async def test_check_transaction_unknown_id_answers_31003(client):
    result = await _rpc(client, "CheckTransaction", {"id": _tx_id("unknown")})
    assert result.json()["error"]["code"] == -31003


async def test_perform_transaction_unknown_id_answers_31003(client):
    result = await _rpc(client, "PerformTransaction", {"id": _tx_id("unknown")})
    assert result.json()["error"]["code"] == -31003


async def test_amounts_cross_the_wire_in_tiyin_without_losing_precision():
    """so'm x 100, integers (design/04 §3.8). A float here loses money on sums
    the Agency will actually see."""
    from app.modules.payments import payme

    assert payme.to_tiyin(Decimal("412000.55")) == 41_200_055
    assert payme.from_tiyin(41_200_055) == Decimal("412000.55")
    assert payme.from_tiyin(payme.to_tiyin(Decimal("0.01"))) == Decimal("0.01")


async def test_check_perform_transaction_never_mutates(db, client, pending_invoice):
    """The brief's own method table: CheckPerformTransaction only PREVIEWS —
    the invoice must still be pending, untouched, afterward."""
    await _rpc(
        client,
        "CheckPerformTransaction",
        {
            "amount": int(pending_invoice.amount * 100),
            "account": {"id": pending_invoice.number},
        },
    )
    await db.refresh(pending_invoice)
    assert pending_invoice.status == "pending"


async def test_check_transaction_never_mutates(db, client, pending_invoice):
    """The brief's own method table: CheckTransaction "never mutates"."""
    tx_id = _tx_id("check-never-mutates")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)

    checked = await _rpc(client, "CheckTransaction", {"id": tx_id})
    assert checked.json()["result"]["state"] == 1
    assert checked.json()["result"]["perform_time"] == 0
    assert checked.json()["result"]["cancel_time"] == 0
    assert checked.json()["result"]["reason"] is None


async def test_check_transaction_does_not_auto_cancel_an_expired_one(
    db, client, pending_invoice, frozen_clock
):
    """Ruling 4 names `CreateTransaction`/`PerformTransaction`, not
    `CheckTransaction` — reading an EXPIRED transaction through `Check` must
    not itself trigger the 12h auto-cancel side effect; it must report the
    transaction exactly as it still stands (state `1`, no `cancel_time`)."""
    tx_id = _tx_id("check-no-auto-cancel")
    params = {
        "id": tx_id,
        "time": 1_800_000_000_000,
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    await _rpc(client, "CreateTransaction", params)

    frozen_clock.advance(timedelta(hours=12, minutes=1))
    checked = await _rpc(client, "CheckTransaction", {"id": tx_id})
    assert checked.json()["result"]["state"] == 1
    assert checked.json()["result"]["cancel_time"] == 0
    assert checked.json()["result"]["reason"] is None


# --- task 5: GetStatement and ChangePassword ---------------------------------


async def test_get_statement_returns_only_transactions_in_the_window(
    db, client, pending_invoice, frozen_clock
):
    """`GetStatement` selects on the row's OWN `received_at` (the same clock
    the 12h timeout uses), never Payme's own `time` param. Two transactions
    two hours apart, a window that brackets only the second — scoped to the
    two ids THIS test created (lesson: 'The test DB is shared, persistent,
    and never empty'), never a bare `len(...)` over the whole response,
    which every other committed transaction in this shared DB would also
    answer to."""
    params = {
        "amount": int(pending_invoice.amount * 100),
        "account": {"id": pending_invoice.number},
    }
    t0 = frozen_clock.current
    outside = await _rpc(client, "CreateTransaction", {**params, "id": _tx_id("stmt-outside")})
    outside_tx = outside.json()["result"]["transaction"]

    frozen_clock.advance(timedelta(hours=2))
    t2 = frozen_clock.current
    inside = await _rpc(client, "CreateTransaction", {**params, "id": _tx_id("stmt-inside")})
    inside_tx = inside.json()["result"]["transaction"]

    frozen_clock.advance(timedelta(hours=2))

    window_from = int((t0 + timedelta(hours=1)).timestamp() * 1000)
    window_to = int((t2 + timedelta(hours=1)).timestamp() * 1000)
    statement = await _rpc(client, "GetStatement", {"from": window_from, "to": window_to})
    transactions = statement.json()["result"]["transactions"]

    ids_in_window = {row["transaction"] for row in transactions}
    assert inside_tx in ids_in_window
    assert outside_tx not in ids_in_window

    entry = next(row for row in transactions if row["transaction"] == inside_tx)
    assert entry["account"] == {"id": pending_invoice.number}
    assert entry["amount"] == int(pending_invoice.amount * 100)
    assert entry["state"] == 1


async def test_get_statement_never_mutates(db, client, pending_invoice):
    """The brief's own method table, same invariant as `CheckTransaction`."""
    tx_id = _tx_id("stmt-no-mutate")
    await _rpc(
        client,
        "CreateTransaction",
        {
            "id": tx_id,
            "amount": int(pending_invoice.amount * 100),
            "account": {"id": pending_invoice.number},
        },
    )
    await _rpc(client, "GetStatement", {"from": 0, "to": 99_999_999_999_999})
    checked = await _rpc(client, "CheckTransaction", {"id": tx_id})
    assert checked.json()["result"]["state"] == 1


@pytest.fixture
async def _reset_cashbox_key_hash(db):
    """`ChangePassword` writes a system-wide `payme_cashbox_key_hash`
    override — every OTHER test's `_auth()` (default key
    'test-cashbox-key') and every FUTURE run against the shared, PERSISTENT
    test DB depend on that override staying empty (lesson: 'The test DB is
    shared, persistent, and never empty' — a successful write is the same
    class of leftover state as the lesson's own 'a refused action leaves
    its row'). Teardown deletes the row and invalidates the process cache
    regardless of how the test using it exits, so every sibling test keeps
    authenticating against `PAYME_CASHBOX_KEY` the old way."""
    yield
    from sqlalchemy import delete

    from app.core import settings_store
    from app.core.models import SystemSetting

    await db.execute(delete(SystemSetting).where(SystemSetting.key == "payme_cashbox_key_hash"))
    await db.commit()
    settings_store.invalidate("payme_cashbox_key_hash")


async def test_change_password_rotates_the_cashbox_key(db, client, _reset_cashbox_key_hash):
    """Ruling: `ChangePassword` persists `sha256(new key)` and the OLD key
    must fail `-32504` immediately afterward while the NEW one succeeds —
    proven by `CheckTransaction` on a made-up id: `-32504` means auth never
    even reached the dispatcher, `-31003` means it did (and simply found no
    such transaction, which is expected for a made-up id)."""
    new_key = f"rotated-{uuid.uuid4().hex[:16]}"

    rotated = await _rpc(client, "ChangePassword", {"password": new_key})
    assert rotated.json()["result"] == {"success": True}

    old_key_call = await _rpc(
        client, "CheckTransaction", {"id": "whatever"}, key="test-cashbox-key"
    )
    assert old_key_call.json()["error"]["code"] == -32504

    new_key_call = await _rpc(client, "CheckTransaction", {"id": "whatever"}, key=new_key)
    assert new_key_call.json()["error"]["code"] == -31003


async def test_change_password_without_a_new_password_answers_32504(client):
    result = await _rpc(client, "ChangePassword", {})
    assert result.json()["error"]["code"] == -32504
