"""audit_log

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-27 18:07:17.265947

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=True),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("old_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("new_value", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("basis", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("extra", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "result IN ('success', 'denied', 'error')", name=op.f("ck_audit_log_result_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_log_object",
        "audit_log",
        ["object_type", "object_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_audit_log_occurred_at_brin",
        "audit_log",
        ["occurred_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_index("ix_audit_log_user", "audit_log", ["user_id", "occurred_at"], unique=False)
    # ### end Alembic commands ###

    op.execute(
        """
        CREATE FUNCTION audit_log_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'audit_log is append-only (incident RI-06)';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER audit_log_append_only "
        "BEFORE UPDATE OR DELETE ON audit_log "
        "FOR EACH ROW EXECUTE FUNCTION audit_log_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER audit_log_no_truncate "
        "BEFORE TRUNCATE ON audit_log "
        "FOR EACH STATEMENT EXECUTE FUNCTION audit_log_forbid_mutation()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS audit_log_no_truncate ON audit_log")
    op.execute("DROP TRIGGER IF EXISTS audit_log_append_only ON audit_log")
    op.execute("DROP FUNCTION IF EXISTS audit_log_forbid_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_log_user", table_name="audit_log")
    op.drop_index("ix_audit_log_occurred_at_brin", table_name="audit_log", postgresql_using="brin")
    op.drop_index("ix_audit_log_object", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
