"""auth

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-27 20:36:13.315192

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | Sequence[str] | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("max_approve_amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.Column("max_approve_area", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("code", name=op.f("uq_roles_code")),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_role_permissions_role_id_roles")
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_code", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("login", postgresql.CITEXT(), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("pinfl", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("position", sa.Text(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("district_id", sa.Uuid(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("phone_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("mfa_secret", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "pinfl IS NULL OR pinfl ~ '^\\d{14}$'", name=op.f("ck_users_pinfl_format")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'blocked', 'deleted')", name=op.f("ck_users_status_valid")
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], name=op.f("fk_users_role_id_roles")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("login", name=op.f("uq_users_login")),
        sa.UniqueConstraint("pinfl", name=op.f("uq_users_pinfl")),
    )
    op.create_table(
        "otp_codes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("target_type", sa.Text(), nullable=True),
        sa.Column("target", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("code_hash", sa.Text(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "purpose IN ('phone_verify', 'email_verify', 'mfa', 'password_reset')",
            name=op.f("ck_otp_codes_purpose_valid"),
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_otp_codes_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_otp_codes")),
    )
    op.create_index("ix_otp_codes_code_hash", "otp_codes", ["code_hash"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("csrf_token", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        # TypeDecorator renders as app.db.IPAddressString in autogenerate; INET is
        # the real DDL type.
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_sessions_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_sessions_token_hash")),
    )
    op.create_index("ix_sessions_user", "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_permissions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("permission_code", sa.Text(), nullable=False),
        sa.Column("granted_by", sa.Uuid(), nullable=True),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_by"], ["users.id"], name=op.f("fk_user_permissions_granted_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_permissions_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "permission_code", name=op.f("pk_user_permissions")),
    )
    # ### end Alembic commands ###

    # 11 system roles (tz/03 + chief_forester, decision #32); fixed ids for reproducibility
    roles = [
        (
            "0198f000-0000-7000-8000-000000000001",
            "sys_admin",
            "Тизим администратори",
            "System administrator",
        ),
        (
            "0198f000-0000-7000-8000-000000000002",
            "central_admin",
            "Марказий аппарат ходими",
            "Central office staff",
        ),
        (
            "0198f000-0000-7000-8000-000000000003",
            "leadership",
            "Агентлик раҳбарияти",
            "Agency leadership",
        ),
        (
            "0198f000-0000-7000-8000-000000000004",
            "executor_staff",
            "Ижрочи ходим",
            "Forestry executor staff",
        ),
        (
            "0198f000-0000-7000-8000-000000000005",
            "gis_specialist",
            "GIS мутахассиси",
            "GIS/norms specialist",
        ),
        (
            "0198f000-0000-7000-8000-000000000006",
            "executor_head",
            "Ваколатли шахс",
            "Forestry head",
        ),
        (
            "0198f000-0000-7000-8000-000000000007",
            "chief_forester",
            "Бош ўрмонбеги",
            "Chief forester",
        ),
        ("0198f000-0000-7000-8000-000000000008", "inspector", "Инспектор", "Inspector"),
        ("0198f000-0000-7000-8000-000000000009", "accountant", "Бухгалтер", "Accountant"),
        ("0198f000-0000-7000-8000-00000000000a", "applicant", "Ариза берувчи", "Applicant"),
        ("0198f000-0000-7000-8000-00000000000b", "prosecutor", "Прокурор", "Prosecutor"),
    ]
    for role_id, code, name_cyr, name_en in roles:
        op.execute(
            sa.text(
                "INSERT INTO roles (id, code, name, is_system) "
                # asyncpg needs an explicit uuid cast for text binds.
                "VALUES (CAST(:id AS uuid), :code, "
                "jsonb_build_object('uz_cyrl', :cyr, 'en', :en), true)"
            ).bindparams(id=role_id, code=code, cyr=name_cyr, en=name_en)
        )

    # Close 3.1's deferred FK (ruling 3): NOT VALID first (table has rows), then VALIDATE
    op.create_foreign_key(
        "fk_audit_log_user_id_users",
        "audit_log",
        "users",
        ["user_id"],
        ["id"],
        postgresql_not_valid=True,
    )
    op.execute("ALTER TABLE audit_log VALIDATE CONSTRAINT fk_audit_log_user_id_users")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("fk_audit_log_user_id_users", "audit_log", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_permissions")
    op.drop_index("ix_sessions_user", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_otp_codes_code_hash", table_name="otp_codes")
    op.drop_table("otp_codes")
    op.drop_table("users")
    op.drop_table("role_permissions")
    op.drop_table("roles")
    # ### end Alembic commands ###
