"""admin

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-27 23:31:02.142751

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | Sequence[str] | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "activity_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("quantity_unit", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity_unit IN ('head', 'ton', 'hive', 'ha', 'person', 'unit')",
            name=op.f("ck_activity_types_quantity_unit_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_activity_types_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_activity_types")),
        sa.UniqueConstraint("code", name=op.f("uq_activity_types_code")),
    )
    op.create_table(
        "classifiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classifiers")),
        sa.UniqueConstraint("code", name=op.f("uq_classifiers_code")),
    )
    op.create_table(
        "livestock_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_livestock_types_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_livestock_types")),
        sa.UniqueConstraint("code", name=op.f("uq_livestock_types_code")),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("soato_code", sa.Text(), nullable=True),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("code", name=op.f("uq_regions_code")),
        sa.UniqueConstraint("soato_code", name=op.f("uq_regions_soato_code")),
    )
    op.create_table(
        "classifier_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("classifier_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "props", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_classifier_items_status_valid")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to >= valid_from",
            name=op.f("ck_classifier_items_valid_period"),
        ),
        sa.ForeignKeyConstraint(
            ["classifier_id"],
            ["classifiers.id"],
            name=op.f("fk_classifier_items_classifier_id_classifiers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classifier_items")),
    )
    op.create_index(
        "ix_classifier_items_classifier", "classifier_items", ["classifier_id"], unique=False
    )
    op.create_index(
        "uq_classifier_items_active_code",
        "classifier_items",
        ["classifier_id", "code"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "districts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("soato_code", sa.Text(), nullable=True),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_districts_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_districts")),
        sa.UniqueConstraint("code", name=op.f("uq_districts_code")),
        sa.UniqueConstraint("soato_code", name=op.f("uq_districts_soato_code")),
    )
    op.create_index("ix_districts_region", "districts", ["region_id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("stir", sa.Text(), nullable=True),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("district_id", sa.Uuid(), nullable=True),
        sa.Column(
            "requisites",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'agency') = (parent_id IS NULL)", name=op.f("ck_organizations_root_is_agency")
        ),
        sa.CheckConstraint(
            "kind IN ('agency', 'territorial', 'leshoz', 'bolim', 'aylanma', 'bolak')",
            name=op.f("ck_organizations_kind_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_organizations_status_valid")
        ),
        sa.CheckConstraint(
            "stir IS NULL OR stir ~ '^\\d{9}$'", name=op.f("ck_organizations_stir_format")
        ),
        sa.ForeignKeyConstraint(
            ["district_id"], ["districts.id"], name=op.f("fk_organizations_district_id_districts")
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["organizations.id"],
            name=op.f("fk_organizations_parent_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_organizations_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("code", name=op.f("uq_organizations_code")),
    )
    op.create_index("ix_organizations_district", "organizations", ["district_id"], unique=False)
    op.create_index("ix_organizations_parent", "organizations", ["parent_id"], unique=False)
    op.create_index("ix_organizations_region", "organizations", ["region_id"], unique=False)
    op.create_index(
        "uq_organizations_single_agency",
        "organizations",
        ["kind"],
        unique=True,
        postgresql_where=sa.text("kind = 'agency'"),
    )
    op.create_table(
        "system_settings",
        sa.Column("key", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_system_settings_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_system_settings")),
    )
    # ### end Alembic commands ###

    # Close 3.2a's deferred territory FKs (ruling 4): NOT VALID first, then VALIDATE
    for column, target in (
        ("organization_id", "organizations"),
        ("region_id", "regions"),
        ("district_id", "districts"),
    ):
        name = f"fk_users_{column}_{target}"
        op.create_foreign_key(name, "users", target, [column], ["id"], postgresql_not_valid=True)
        op.execute(f"ALTER TABLE users VALIDATE CONSTRAINT {name}")


def downgrade() -> None:
    """Downgrade schema."""
    for column, target in (
        ("organization_id", "organizations"),
        ("region_id", "regions"),
        ("district_id", "districts"),
    ):
        op.drop_constraint(f"fk_users_{column}_{target}", "users", type_="foreignkey")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_settings")
    op.drop_index(
        "uq_organizations_single_agency",
        table_name="organizations",
        postgresql_where=sa.text("kind = 'agency'"),
    )
    op.drop_index("ix_organizations_region", table_name="organizations")
    op.drop_index("ix_organizations_parent", table_name="organizations")
    op.drop_index("ix_organizations_district", table_name="organizations")
    op.drop_table("organizations")
    op.drop_index("ix_districts_region", table_name="districts")
    op.drop_table("districts")
    op.drop_index(
        "uq_classifier_items_active_code",
        table_name="classifier_items",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_classifier_items_classifier", table_name="classifier_items")
    op.drop_table("classifier_items")
    op.drop_table("regions")
    op.drop_table("livestock_types")
    op.drop_table("classifiers")
    op.drop_table("activity_types")
    # ### end Alembic commands ###
