"""applicants

Revision ID: 0006
Revises: 0005
Create Date: 2026-08-28 12:04:35.705005

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | Sequence[str] | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applicants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("pinfl", sa.Text(), nullable=True),
        sa.Column("stir", sa.Text(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("region_id", sa.Uuid(), nullable=True),
        sa.Column("district_id", sa.Uuid(), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("phone", sa.Text(), nullable=True),
        sa.Column("email", postgresql.CITEXT(), nullable=True),
        sa.Column("requisites", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verify_source", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'individual' AND pinfl IS NOT NULL AND stir IS NULL)"
            " OR (kind = 'legal' AND stir IS NOT NULL AND pinfl IS NULL)",
            name=op.f("ck_applicants_identity_by_kind"),
        ),
        sa.CheckConstraint(
            "kind IN ('individual', 'legal')", name=op.f("ck_applicants_kind_valid")
        ),
        sa.CheckConstraint(
            "pinfl IS NULL OR pinfl ~ '^[0-9]{14}$'", name=op.f("ck_applicants_pinfl_format")
        ),
        sa.CheckConstraint(
            "stir IS NULL OR stir ~ '^[0-9]{9}$'", name=op.f("ck_applicants_stir_format")
        ),
        sa.ForeignKeyConstraint(
            ["district_id"], ["districts.id"], name=op.f("fk_applicants_district_id_districts")
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"], ["users.id"], name=op.f("fk_applicants_owner_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], name=op.f("fk_applicants_region_id_regions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applicants")),
        sa.UniqueConstraint("owner_user_id", name=op.f("uq_applicants_owner_user_id")),
        sa.UniqueConstraint("pinfl", name=op.f("uq_applicants_pinfl")),
        sa.UniqueConstraint("stir", name=op.f("uq_applicants_stir")),
    )
    op.create_table(
        "user_consents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("doc_type", sa.Text(), nullable=False),
        sa.Column("doc_version", sa.Text(), nullable=False),
        sa.Column(
            "accepted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        # TypeDecorator renders as app.db.IPAddressString in autogenerate; INET is
        # the real DDL type.
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.CheckConstraint(
            "doc_type IN ('privacy_policy', 'offer')", name=op.f("ck_user_consents_doc_type_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_consents_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_consents")),
        sa.UniqueConstraint("user_id", "doc_type", "doc_version", name="uq_user_consents_doc"),
    )
    op.create_table(
        "representations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("poa_file_id", sa.Uuid(), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "basis <> 'poa' OR (poa_file_id IS NOT NULL AND valid_until IS NOT NULL)",
            name=op.f("ck_representations_poa_requires_file_and_term"),
        ),
        sa.CheckConstraint(
            "basis IN ('director_registry', 'poa', 'org_eri')",
            name=op.f("ck_representations_basis_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'revoked')",
            name=op.f("ck_representations_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_representations_applicant_id_applicants"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_representations_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_representations")),
    )
    op.create_index("ix_representations_user", "representations", ["user_id"], unique=False)
    op.create_index(
        "uq_representations_active",
        "representations",
        ["applicant_id", "user_id"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.add_column(
        "otp_codes",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "users", sa.Column("oneid_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=True)
    )
    # ### end Alembic commands ###

    # otp_codes now also covers phone/email verify, their verified-tokens, and
    # E-IMZO challenges (not autogenerated: CHECK text changes aren't detected).
    op.drop_constraint("purpose_valid", "otp_codes", type_="check")
    op.create_check_constraint(
        "purpose_valid",
        "otp_codes",
        "purpose IN ('phone_verify', 'email_verify', 'mfa', 'password_reset',"
        " 'phone_verify_token', 'email_verify_token', 'eimzo_challenge')",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("purpose_valid", "otp_codes", type_="check")
    op.create_check_constraint(
        "purpose_valid",
        "otp_codes",
        "purpose IN ('phone_verify', 'email_verify', 'mfa', 'password_reset')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "oneid_profile")
    op.drop_column("otp_codes", "created_at")
    op.drop_index(
        "uq_representations_active",
        table_name="representations",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_index("ix_representations_user", table_name="representations")
    op.drop_table("representations")
    op.drop_table("user_consents")
    op.drop_table("applicants")
    # ### end Alembic commands ###
