"""admin users

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-28 17:51:59.315913

Adds media_files (core) and announcements/announcement_files (admin), closes the
deferred representations.poa_file_id FK from 3.2b, swaps the users.pinfl CHECK to
match ASCII digits only, and adds roles.status. Seeds auth.users.view to the three
roles that need it out of the box (С23).

The poa cleanup below (ruling 6) permanently deletes any basis='poa' representation
whose poa_file_id doesn't resolve — the only pre-prod hard delete this project
sanctions. Those rows are NOT recoverable by downgrade().
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | Sequence[str] | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "announcements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("audience", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("publish_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("publish_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_announcements_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_announcements_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_announcements")),
    )
    op.create_index(
        "ix_announcements_status_window",
        "announcements",
        ["status", "publish_from"],
        unique=False,
    )
    # geoalchemy2.alembic_helpers registers these on `op` at import time (see
    # env.py's render_item/writer); pyright can't see dynamically-registered ops.
    op.create_geospatial_table(  # pyright: ignore[reportAttributeAccessIssue]
        "media_files",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("filename", sa.Text(), nullable=False),
        sa.Column("content_type", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.Text(), nullable=False),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "gps",
            Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("device", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("uploaded_by", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_media_files_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_media_files_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media_files")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_media_files_storage_key")),
    )
    op.create_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_media_files_gps",
        "media_files",
        ["gps"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index("ix_media_files_uploaded_by", "media_files", ["uploaded_by"], unique=False)
    op.create_table(
        "announcement_files",
        sa.Column("announcement_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["announcement_id"],
            ["announcements.id"],
            name=op.f("fk_announcement_files_announcement_id_announcements"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["media_files.id"],
            name=op.f("fk_announcement_files_file_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("announcement_id", "file_id", name=op.f("pk_announcement_files")),
    )
    # ### end Alembic commands ###

    # roles.status: 11 rows already seeded (0003) — add nullable, backfill, then
    # tighten to NOT NULL (no server_default kept, matching the Python-only
    # `default="active"` on the model; a lingering server default would show up
    # as a spurious autogenerate diff).
    op.add_column("roles", sa.Column("status", sa.Text(), nullable=True))
    op.execute("UPDATE roles SET status = 'active'")
    op.alter_column("roles", "status", existing_type=sa.Text(), nullable=False)
    op.create_check_constraint("status_valid", "roles", "status IN ('active', 'archived')")

    # users.pinfl CHECK: PostgreSQL's '\d' matches any Unicode decimal digit, not
    # just ASCII 0-9 (3.2b carry-over) — swap to an explicit [0-9] class, same
    # text already used by applicants.pinfl_format. Short name here (not the
    # fully-qualified "ck_users_pinfl_format"): drop_constraint re-runs it
    # through the naming convention just like create_check_constraint does, so
    # the already-final name would double-prefix to ck_users_ck_users_pinfl_format.
    op.drop_constraint("pinfl_format", "users", type_="check")
    op.create_check_constraint("pinfl_format", "users", "pinfl IS NULL OR pinfl ~ '^[0-9]{14}$'")

    # poa cleanup + FK (ruling 6 — the one sanctioned pre-prod hard delete): at
    # this point media_files is empty, so every basis='poa' representation is
    # necessarily orphaned; drop them before the FK can be validated.
    op.execute(
        """
        DELETE FROM representations r
        WHERE r.basis = 'poa'
          AND NOT EXISTS (SELECT 1 FROM media_files m WHERE m.id = r.poa_file_id)
        """
    )
    op.execute(
        "ALTER TABLE representations ADD CONSTRAINT fk_representations_poa_file_id_media_files "
        "FOREIGN KEY (poa_file_id) REFERENCES media_files (id) NOT VALID"
    )
    op.execute(
        "ALTER TABLE representations VALIDATE CONSTRAINT fk_representations_poa_file_id_media_files"
    )

    # Seeds: auth.users.view granted to the three roles that need it out of the
    # box (С23); fixed role ids from migration 0003.
    for role_id in (
        "0198f000-0000-7000-8000-000000000002",  # central_admin
        "0198f000-0000-7000-8000-000000000003",  # leadership
        "0198f000-0000-7000-8000-000000000006",  # executor_head
    ):
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_code) "
                # asyncpg needs an explicit uuid cast for text binds.
                "VALUES (CAST(:rid AS uuid), 'auth.users.view')"
            ).bindparams(rid=role_id)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeds
    op.execute("DELETE FROM role_permissions WHERE permission_code = 'auth.users.view'")

    # poa FK — the rows upgrade() deleted are not restorable.
    op.drop_constraint(
        "fk_representations_poa_file_id_media_files", "representations", type_="foreignkey"
    )

    # users.pinfl CHECK: restore the pre-3.3b (Unicode-matching) text. Short
    # constraint names (see the matching comment in upgrade()).
    op.drop_constraint("pinfl_format", "users", type_="check")
    op.create_check_constraint("pinfl_format", "users", "pinfl IS NULL OR pinfl ~ '^\\d{14}$'")

    # roles.status
    op.drop_constraint("status_valid", "roles", type_="check")
    op.drop_column("roles", "status")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("announcement_files")
    op.drop_index("ix_media_files_uploaded_by", table_name="media_files")
    # geoalchemy2.alembic_helpers registers these on `op` at import time; see the
    # matching comment in upgrade().
    op.drop_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_media_files_gps", table_name="media_files", postgresql_using="gist", column_name="gps"
    )
    op.drop_geospatial_table("media_files")  # pyright: ignore[reportAttributeAccessIssue]
    op.drop_index("ix_announcements_status_window", table_name="announcements")
    op.drop_table("announcements")
    # ### end Alembic commands ###
