"""integrations core

Adds outbox_messages, inbound_dead_letters, integration_log (design/02 §
integrations) and idempotency_keys (core), and seeds admin.integrations.view /
admin.integrations.manage to central_admin.

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-29 11:58:14.060901

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | Sequence[str] | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_log",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("direction", sa.Text(), nullable=False),
        sa.Column("system", sa.Text(), nullable=False),
        sa.Column("endpoint", sa.Text(), nullable=False),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Text(), nullable=True),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.Text(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.CheckConstraint(
            "direction IN ('in', 'out')", name=op.f("ck_integration_log_direction_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_log")),
    )
    op.create_index(
        "ix_integration_log_occurred_at",
        "integration_log",
        ["occurred_at"],
        unique=False,
        postgresql_using="brin",
    )
    op.create_table(
        "outbox_messages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("destination", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'delivering', 'delivered', 'dead')",
            name=op.f("ck_outbox_messages_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_messages")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbox_messages_idempotency_key")),
    )
    op.create_index(
        "ix_outbox_messages_due", "outbox_messages", ["status", "next_attempt_at"], unique=False
    )
    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.Text(), nullable=False),
        sa.Column("route", sa.Text(), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_idempotency_keys_user_id_users")
        ),
        sa.PrimaryKeyConstraint("key", "user_id", name=op.f("pk_idempotency_keys")),
    )
    op.create_table(
        "inbound_dead_letters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("processed_by", sa.Uuid(), nullable=True),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('new', 'reprocessed', 'discarded')",
            name=op.f("ck_inbound_dead_letters_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["processed_by"], ["users.id"], name=op.f("fk_inbound_dead_letters_processed_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbound_dead_letters")),
    )
    # ### end Alembic commands ###

    # Seeds: admin.integrations.view / admin.integrations.manage granted to
    # central_admin out of the box (fixed role id from migration 0003).
    op.execute(
        "INSERT INTO role_permissions (role_id, permission_code) VALUES "
        "('0198f000-0000-7000-8000-000000000002', 'admin.integrations.view'), "
        "('0198f000-0000-7000-8000-000000000002', 'admin.integrations.manage')"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeds
    op.execute(
        "DELETE FROM role_permissions WHERE permission_code IN "
        "('admin.integrations.view', 'admin.integrations.manage')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inbound_dead_letters")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_outbox_messages_due", table_name="outbox_messages")
    op.drop_table("outbox_messages")
    op.drop_index(
        "ix_integration_log_occurred_at", table_name="integration_log", postgresql_using="brin"
    )
    op.drop_table("integration_log")
    # ### end Alembic commands ###
