"""notifications

Adds notification_templates and notifications (design/02 § notifications,
corrected by plan 03.5 rulings 5-8), users.language and outbox_messages.alerted_at,
and seeds notifications.templates.manage to central_admin plus the initial set of
template texts (SEED_TEMPLATES) — SMS bodies stay short, a Cyrillic SMS part bills
at 70 characters (ruling 20).

Revision ID: 0009
Revises: 0008
Create Date: 2026-08-29 18:03:53.016531

"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0009"
down_revision: str | Sequence[str] | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_BODIES: dict[str, dict[str, str]] = {
    "application.submitted": {
        "uz_cyrl": "Ариза {application_number} қабул қилинди. Ҳолатини шахсий кабинетда кузатинг.",
        "ru": "Заявка {application_number} принята. Статус — в личном кабинете.",
    },
    "application.approved": {
        "uz_cyrl": "Ариза {application_number} маъқулланди.",
        "ru": "Заявка {application_number} одобрена.",
    },
    "application.rejected": {
        "uz_cyrl": "Ариза {application_number} рад этилди. Сабаби: {reason}",
        "ru": "Заявка {application_number} отклонена. Причина: {reason}",
    },
    "invoice.issued": {
        "uz_cyrl": "{application_number} аризаси бўйича {amount} сўм тўлов эълон қилинди."
        " Муддат: {due_date}.",
        "ru": "По заявке {application_number} выставлен счёт на {amount} сум. Срок: {due_date}.",
    },
    "payment.confirmed": {
        "uz_cyrl": "{application_number} аризаси бўйича {amount} сўм тўлов тасдиқланди.",
        "ru": "Оплата {amount} сум по заявке {application_number} подтверждена.",
    },
    "permit.issued": {
        "uz_cyrl": "Рухсатнома {permit_number} расмийлаштирилди."
        " Муддати: {valid_from} — {valid_to}.",
        "ru": "Разрешение {permit_number} оформлено. Срок: {valid_from} — {valid_to}.",
    },
}

SEED_TEMPLATES: list[tuple[str, str, dict[str, str]]] = [
    (event_code, channel, body)
    for event_code, body in _BODIES.items()
    for channel in ("inapp", "sms")
] + [
    (
        "system.outbox_dead",
        "inapp",
        {
            "uz_cyrl": "Интеграция хатоси: {destination} йўналиши бўйича"
            " {count} та хабар етказилмади.",
            "ru": "Ошибка интеграции: не доставлено сообщений — {count}"
            " (направление {destination}).",
        },
    )
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("event_code", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("subject", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("body", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('inapp', 'sms', 'email')",
            name=op.f("ck_notification_templates_channel_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_notification_templates_status_valid")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_notification_templates_version_positive")),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_notification_templates_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_templates")),
        sa.UniqueConstraint("event_code", "channel", "version", name="uq_version"),
    )
    op.create_index(
        "uq_notification_templates_active",
        "notification_templates",
        ["event_code", "channel"],
        unique=True,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("event_code", sa.Text(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=True),
        sa.Column("params", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("rendered_text", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("outbox_message_id", sa.Uuid(), nullable=True),
        sa.Column("provider_message_id", sa.Text(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("object_type", sa.Text(), nullable=True),
        sa.Column("object_id", sa.Uuid(), nullable=True),
        sa.Column("correlation_id", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "channel IN ('inapp', 'sms', 'email')", name=op.f("ck_notifications_channel_valid")
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'sent', 'delivered', 'failed')",
            name=op.f("ck_notifications_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["outbox_message_id"],
            ["outbox_messages.id"],
            name=op.f("fk_notifications_outbox_message_id_outbox_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["notification_templates.id"],
            name=op.f("fk_notifications_template_id_notification_templates"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_inbox", "notifications", ["recipient_user_id", "created_at"], unique=False
    )
    op.create_index(
        "ix_notifications_provider_message_id",
        "notifications",
        ["provider_message_id"],
        unique=False,
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.add_column(
        "outbox_messages", sa.Column("alerted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("language", sa.Text(), server_default="uz_cyrl", nullable=False)
    )
    op.create_check_constraint(
        op.f("ck_users_language_valid"),
        "users",
        "language IN ('uz_cyrl', 'uz_latn', 'ru', 'kaa', 'en')",
    )
    # ### end Alembic commands ###

    # Permission code for the template CRUD, granted to central_admin out of the box
    # (fixed role id from migration 0003).
    op.execute(
        "INSERT INTO role_permissions (role_id, permission_code) VALUES "
        "('0198f000-0000-7000-8000-000000000002', 'notifications.templates.manage')"
    )
    templates = sa.table(
        "notification_templates",
        sa.column("id", sa.Uuid()),
        sa.column("event_code", sa.Text()),
        sa.column("channel", sa.Text()),
        sa.column("body", postgresql.JSONB(astext_type=sa.Text())),
        sa.column("version", sa.Integer()),
        sa.column("status", sa.Text()),
    )
    op.bulk_insert(
        templates,
        [
            {
                # Deliberately uuid4(), not app.db.uuid7 — migrations must not depend
                # on app code that could move/rename later; ordering locality is moot
                # for 13 rows anyway (0005 made the same call with gen_random_uuid()).
                "id": uuid.uuid4(),
                "event_code": event_code,
                "channel": channel,
                "body": body,
                "version": 1,
                "status": "active",
            }
            for event_code, channel, body in SEED_TEMPLATES
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeds
    op.execute(
        "DELETE FROM role_permissions WHERE permission_code = 'notifications.templates.manage'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_users_language_valid"), "users", type_="check")
    op.drop_column("users", "language")
    op.drop_column("outbox_messages", "alerted_at")
    op.drop_index(
        "ix_notifications_provider_message_id",
        table_name="notifications",
        postgresql_where=sa.text("provider_message_id IS NOT NULL"),
    )
    op.drop_index("ix_notifications_inbox", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(
        "uq_notification_templates_active",
        table_name="notification_templates",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("notification_templates")
    # ### end Alembic commands ###
