"""gis

Spatial core (design/02 § gis, corrected by plan 03.6a): the 15-layer catalogue,
contours + versioned geometry (Draft→Review→Approved→Published→Archived), the
restriction/fire-ban layer objects (layer_features) and the geodata import journal
(gis_imports). Seeds the 15 layers of tz/07 (ruling 19: a fixed catalogue, not
admin CRUD), grants gis.contours.manage/approve and gis.layers.manage to the roles
of ruling 17, and seeds the gis.import.finished notification template.

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-30 01:34:28.788480

"""

import json
import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geometry
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | Sequence[str] | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


LAYER_SEED: list[tuple[str, str, str, str, bool]] = [
    # code, uz_cyrl, ru, geometry_type, is_public
    ("forest_fund", "Ўрмон фонди чегаралари", "Границы лесного фонда", "MULTIPOLYGON", True),
    ("org_boundaries", "Ташкилот чегаралари", "Границы организаций", "MULTIPOLYGON", True),
    ("contours", "Контурлар", "Контуры", "MULTIPOLYGON", False),
    ("pastures", "Яйловлар", "Пастбища", "MULTIPOLYGON", False),
    ("hayfields", "Пичанзорлар", "Сенокосы", "MULTIPOLYGON", False),
    ("apiaries", "Асаларичилик жойлари", "Пасеки", "MULTIPOLYGON", False),
    ("recreation", "Рекреация ҳудудлари", "Рекреация", "MULTIPOLYGON", False),
    ("restrictions", "Чекловлар", "Ограничения", "GEOMETRY", False),
    ("protection", "Муҳофаза зоналари", "Охранные зоны", "MULTIPOLYGON", False),
    ("rotation", "Ротация", "Ротация", "MULTIPOLYGON", False),
    ("rest_calendar", "Дам бериш тақвими", "Календарь отдыха", "MULTIPOLYGON", False),
    ("water_points", "Сув нуқталари", "Водные точки", "POINT", False),
    ("cattle_corridors", "Чорва йўлаклари", "Скотопрогонные коридоры", "LINESTRING", False),
    ("fire_bans", "Ёнғин тақиқлари", "Пожарные запреты", "MULTIPOLYGON", True),
    (
        "special_areas",
        "Махсус ажратилган майдонлар",
        "Специально отведённые площадки",
        "MULTIPOLYGON",
        True,
    ),
]

# Ruling 17. NOTE: the plan text says "rahbar", but no such role code exists —
# migration 0003 seeded the agency-leadership role as "leadership" (name.uz_cyrl
# "Агентлик раҳбарияти", the plan's "rahbar" spelled out). Granting to a
# nonexistent code would silently insert zero rows (INSERT ... SELECT ... WHERE
# code = :role matches nothing, ON CONFLICT DO NOTHING hides it further) — the
# exact silent-failure shape .claude/lessons.md warns about, so this grants to
# the role that actually exists.
ROLE_GRANTS: list[tuple[str, str]] = [
    ("gis_specialist", "gis.contours.manage"),
    ("gis_specialist", "gis.layers.manage"),
    ("central_admin", "gis.layers.manage"),
    ("leadership", "gis.contours.approve"),
    ("chief_forester", "gis.contours.approve"),
]

IMPORT_TEMPLATE = {
    "uz_cyrl": "Импорт тугади: {layer}, {created} та объект юкланди ({status}).",
    "ru": "Импорт завершён: {layer}, загружено объектов — {created} ({status}).",
}


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gis_layers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("geometry_type", sa.Text(), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("style", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "geometry_type IN ('POINT', 'LINESTRING', 'POLYGON', 'MULTIPOLYGON', 'GEOMETRY')",
            name=op.f("ck_gis_layers_geometry_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_gis_layers_status_valid")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gis_layers")),
        sa.UniqueConstraint("code", name=op.f("uq_gis_layers_code")),
    )
    op.create_table(
        "contours",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("layer_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("number", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('contour', 'subcontour')", name=op.f("ck_contours_kind_valid")
        ),
        sa.CheckConstraint(
            "parent_id IS NULL OR kind = 'subcontour'",
            name=op.f("ck_contours_parent_needs_subcontour"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'archived')", name=op.f("ck_contours_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_contours_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["layer_id"], ["gis_layers.id"], name=op.f("fk_contours_layer_id_gis_layers")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_contours_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["contours.id"], name=op.f("fk_contours_parent_id_contours")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contours")),
        sa.UniqueConstraint("organization_id", "number", name="uq_contour_number"),
    )
    op.create_index(op.f("ix_contours_layer_id"), "contours", ["layer_id"], unique=False)
    op.create_index(
        op.f("ix_contours_organization_id"), "contours", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_contours_parent_id"), "contours", ["parent_id"], unique=False)
    op.create_table(
        "gis_imports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("layer_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("approval_doc_id", sa.Uuid(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column("attribute_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("error_report", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("stats", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_by", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('shp', 'geojson', 'kml', 'kmz', 'gpkg', 'csv', 'zip')",
            name=op.f("ck_gis_imports_format_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'review', 'approved', 'done', 'failed')",
            name=op.f("ck_gis_imports_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_doc_id"],
            ["media_files.id"],
            name=op.f("fk_gis_imports_approval_doc_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_gis_imports_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["media_files.id"], name=op.f("fk_gis_imports_file_id_media_files")
        ),
        sa.ForeignKeyConstraint(
            ["layer_id"], ["gis_layers.id"], name=op.f("fk_gis_imports_layer_id_gis_layers")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_gis_imports_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["started_by"], ["users.id"], name=op.f("fk_gis_imports_started_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gis_imports")),
    )
    op.create_index(op.f("ix_gis_imports_layer_id"), "gis_imports", ["layer_id"], unique=False)
    op.create_index(
        op.f("ix_gis_imports_organization_id"), "gis_imports", ["organization_id"], unique=False
    )
    op.create_index("ix_gis_imports_pending", "gis_imports", ["status", "created_at"], unique=False)
    # geoalchemy2.alembic_helpers registers these on `op` at import time (see
    # env.py's render_item/writer); pyright can't see dynamically-registered ops.
    op.create_geospatial_table(  # pyright: ignore[reportAttributeAccessIssue]
        "contour_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contour_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column(
            "geom",
            Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("area_ha", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("declared_area_ha", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("accuracy_m", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("survey_date", sa.Date(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("approval_doc_id", sa.Uuid(), nullable=True),
        sa.Column("import_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source IN ('cadastre', 'survey', 'aerial', 'gps', 'import')",
            name=op.f("ck_contour_versions_source_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'published' OR approval_doc_id IS NOT NULL",
            name=op.f("ck_contour_versions_published_needs_doc"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'review', 'approved', 'published', 'archived')",
            name=op.f("ck_contour_versions_status_valid"),
        ),
        sa.CheckConstraint("area_ha > 0", name=op.f("ck_contour_versions_area_positive")),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from",
            name=op.f("ck_contour_versions_effective_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_doc_id"],
            ["media_files.id"],
            name=op.f("fk_contour_versions_approval_doc_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_contour_versions_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["contour_id"], ["contours.id"], name=op.f("fk_contour_versions_contour_id_contours")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_contour_versions_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["gis_imports.id"],
            name=op.f("fk_contour_versions_import_id_gis_imports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contour_versions")),
        sa.UniqueConstraint("contour_id", "version_no", name="uq_contour_version_no"),
    )
    op.create_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_contour_versions_geom",
        "contour_versions",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_contour_versions_contour_id"), "contour_versions", ["contour_id"], unique=False
    )
    op.create_index(
        op.f("ix_contour_versions_import_id"), "contour_versions", ["import_id"], unique=False
    )
    op.create_index(
        "uq_contour_published_version",
        "contour_versions",
        ["contour_id"],
        unique=True,
        postgresql_where=sa.text("status = 'published'"),
    )
    op.create_geospatial_table(  # pyright: ignore[reportAttributeAccessIssue]
        "layer_features",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("layer_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "geom",
            Geometry(
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("props", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("approval_doc_id", sa.Uuid(), nullable=True),
        sa.Column("import_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_layer_features_status_valid"),
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name=op.f("ck_layer_features_validity_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_doc_id"],
            ["media_files.id"],
            name=op.f("fk_layer_features_approval_doc_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_layer_features_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["gis_imports.id"],
            name=op.f("fk_layer_features_import_id_gis_imports"),
        ),
        sa.ForeignKeyConstraint(
            ["layer_id"], ["gis_layers.id"], name=op.f("fk_layer_features_layer_id_gis_layers")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_layer_features_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_layer_features")),
    )
    op.create_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_layer_features_geom",
        "layer_features",
        ["geom"],
        unique=False,
        postgresql_using="gist",
        postgresql_ops={},
    )
    op.create_index(
        op.f("ix_layer_features_import_id"), "layer_features", ["import_id"], unique=False
    )
    op.create_index(
        op.f("ix_layer_features_layer_id"), "layer_features", ["layer_id"], unique=False
    )
    op.create_index(
        op.f("ix_layer_features_organization_id"),
        "layer_features",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    layers = sa.table(
        "gis_layers",
        sa.column("id", sa.Uuid()),
        sa.column("code", sa.Text()),
        sa.column("name", postgresql.JSONB()),
        sa.column("geometry_type", sa.Text()),
        sa.column("is_public", sa.Boolean()),
        sa.column("style", postgresql.JSONB()),
        sa.column("status", sa.Text()),
    )
    op.bulk_insert(
        layers,
        [
            {
                # Deliberately uuid4(), not app.db.uuid7 — migrations must not depend
                # on app code that could move/rename later (same call as 0009).
                "id": uuid.uuid4(),
                "code": code,
                "name": {"uz_cyrl": uz, "ru": ru},
                "geometry_type": geometry_type,
                "is_public": is_public,
                "style": {},
                "status": "active",
            }
            for code, uz, ru, geometry_type, is_public in LAYER_SEED
        ],
    )
    for role_code, permission_code in ROLE_GRANTS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_code)"
                " SELECT id, :perm FROM roles WHERE code = :role"
                " ON CONFLICT DO NOTHING"
            ).bindparams(perm=permission_code, role=role_code)
        )
    # A plain text bind cast server-side, not a JSONB-typed bind param:
    # sa.literal(value, postgresql.JSONB) sends the BindParameter construct itself
    # as the value to asyncpg's JSONB codec instead of the serialized text, which
    # asyncpg rejects (DataError: "... has no attribute 'encode'"). asyncpg needs
    # an explicit cast for text binds anyway (see 0003_auth's CAST(:id AS uuid)).
    op.execute(
        sa.text(
            "INSERT INTO notification_templates (id, event_code, channel, body, version, status)"
            " VALUES (gen_random_uuid(), 'gis.import.finished', 'inapp',"
            " CAST(:body AS jsonb), 1, 'active')"
        ).bindparams(body=json.dumps(IMPORT_TEMPLATE))
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeds — a downgrade must delete the rows its upgrade made legal (lesson).
    op.execute(
        sa.text("DELETE FROM notification_templates WHERE event_code = 'gis.import.finished'")
    )
    op.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_code IN"
            " ('gis.contours.manage', 'gis.contours.approve', 'gis.layers.manage')"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_layer_features_organization_id"), table_name="layer_features")
    op.drop_index(op.f("ix_layer_features_layer_id"), table_name="layer_features")
    op.drop_index(op.f("ix_layer_features_import_id"), table_name="layer_features")
    op.drop_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_layer_features_geom",
        table_name="layer_features",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("layer_features")  # pyright: ignore[reportAttributeAccessIssue]
    op.drop_index(
        "uq_contour_published_version",
        table_name="contour_versions",
        postgresql_where=sa.text("status = 'published'"),
    )
    op.drop_index(op.f("ix_contour_versions_import_id"), table_name="contour_versions")
    op.drop_index(op.f("ix_contour_versions_contour_id"), table_name="contour_versions")
    op.drop_geospatial_index(  # pyright: ignore[reportAttributeAccessIssue]
        "idx_contour_versions_geom",
        table_name="contour_versions",
        postgresql_using="gist",
        column_name="geom",
    )
    op.drop_geospatial_table("contour_versions")  # pyright: ignore[reportAttributeAccessIssue]
    op.drop_index("ix_gis_imports_pending", table_name="gis_imports")
    op.drop_index(op.f("ix_gis_imports_organization_id"), table_name="gis_imports")
    op.drop_index(op.f("ix_gis_imports_layer_id"), table_name="gis_imports")
    op.drop_table("gis_imports")
    op.drop_index(op.f("ix_contours_parent_id"), table_name="contours")
    op.drop_index(op.f("ix_contours_organization_id"), table_name="contours")
    op.drop_index(op.f("ix_contours_layer_id"), table_name="contours")
    op.drop_table("contours")
    op.drop_table("gis_layers")
    # ### end Alembic commands ###
