"""norms

Schema for stage 3.7 (design/02 § norms, corrected by plan 03.7): rule_parameters,
tariffs, norms and the immutable calculations ledger. Each of the first three is
versioned by an effective period and carries a partial GiST EXCLUDE constraint
forbidding two published rows in force at once for the same key — SQLAlchemy
cannot express EXCLUDE, so the three are hand-written here (btree_gist, already
installed by 0001, is what lets a scalar `=` sit inside the same GiST index as
`&&` on the daterange). `calculations` is append-only via a BEFORE
UPDATE/DELETE/TRUNCATE trigger, mirroring audit_log's own (0002). Also widens
activity_types.quantity_unit's CHECK to accept 'person_day'/'m3' (ruling 2 — the
real VMQ 278 units; the row data itself is corrected by 0012) and grants the five
new permission codes to gis_specialist/leadership/central_admin (ruling 16).

Revision ID: 0011
Revises: 0010
Create Date: 2026-08-30 13:46:34.454405

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rule_parameters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("unit", sa.Text(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'published' OR created_by IS NULL "
            "OR (approved_by IS NOT NULL AND approved_by <> created_by)",
            name=op.f("ck_rule_parameters_maker_checker"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')",
            name=op.f("ck_rule_parameters_status_valid"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_rule_parameters_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_rule_parameters_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_rule_parameters_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rule_parameters")),
    )
    op.create_index(
        "ix_rule_parameters_lookup",
        "rule_parameters",
        ["code", "status", "effective_from"],
        unique=False,
    )
    op.create_table(
        "tariffs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("activity_type_id", sa.Uuid(), nullable=False),
        sa.Column("livestock_group", sa.Text(), nullable=True),
        sa.Column("coefficient", sa.Numeric(precision=12, scale=6), nullable=False),
        sa.Column("quantity_unit", sa.Text(), nullable=False),
        sa.Column("benefit_modifiers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("basis", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "livestock_group IS NULL OR livestock_group IN "
            "('large_adult', 'large_young', 'small_adult', 'small_young')",
            name=op.f("ck_tariffs_livestock_group_valid"),
        ),
        sa.CheckConstraint(
            "status <> 'published' OR created_by IS NULL "
            "OR (approved_by IS NOT NULL AND approved_by <> created_by)",
            name=op.f("ck_tariffs_maker_checker"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'archived')", name=op.f("ck_tariffs_status_valid")
        ),
        sa.CheckConstraint("coefficient >= 0", name=op.f("ck_tariffs_coefficient_non_negative")),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_tariffs_period_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_type_id"],
            ["activity_types.id"],
            name=op.f("fk_tariffs_activity_type_id_activity_types"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_tariffs_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_tariffs_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tariffs")),
    )
    op.create_index(
        "ix_tariffs_lookup",
        "tariffs",
        ["activity_type_id", "status", "effective_from"],
        unique=False,
    )
    op.create_table(
        "calculations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=True),
        sa.Column("contour_id", sa.Uuid(), nullable=True),
        sa.Column("activity_type_id", sa.Uuid(), nullable=False),
        sa.Column("rule_code_version", sa.Text(), nullable=False),
        sa.Column("input_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("used_sb", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("max_sb", sa.Integer(), nullable=True),
        sa.Column("remaining_sb", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("breakdown", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_calculations_amount_non_negative")),
        sa.ForeignKeyConstraint(
            ["activity_type_id"],
            ["activity_types.id"],
            name=op.f("fk_calculations_activity_type_id_activity_types"),
        ),
        sa.ForeignKeyConstraint(
            ["contour_id"], ["contours.id"], name=op.f("fk_calculations_contour_id_contours")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_calculations_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_calculations")),
    )
    op.create_index(
        "ix_calculations_application",
        "calculations",
        ["application_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "norms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("contour_id", sa.Uuid(), nullable=False),
        sa.Column("activity_type_id", sa.Uuid(), nullable=False),
        sa.Column("yield_c_per_ha", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("season", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rotation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("max_sb", sa.Integer(), nullable=True),
        sa.Column("geobotanic_doc_id", sa.Uuid(), nullable=True),
        sa.Column("approval_doc_id", sa.Uuid(), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'published' OR approval_doc_id IS NOT NULL",
            name=op.f("ck_norms_published_needs_doc"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'review', 'approved', 'published', 'archived')",
            name=op.f("ck_norms_status_valid"),
        ),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to >= effective_from",
            name=op.f("ck_norms_period_valid"),
        ),
        sa.CheckConstraint(
            "yield_c_per_ha IS NULL OR yield_c_per_ha >= 0", name=op.f("ck_norms_yield_valid")
        ),
        sa.ForeignKeyConstraint(
            ["activity_type_id"],
            ["activity_types.id"],
            name=op.f("fk_norms_activity_type_id_activity_types"),
        ),
        sa.ForeignKeyConstraint(
            ["approval_doc_id"],
            ["media_files.id"],
            name=op.f("fk_norms_approval_doc_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_norms_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["contour_id"], ["contours.id"], name=op.f("fk_norms_contour_id_contours")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_norms_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["geobotanic_doc_id"],
            ["media_files.id"],
            name=op.f("fk_norms_geobotanic_doc_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_norms")),
    )
    op.create_index(
        "ix_norms_lookup",
        "norms",
        ["contour_id", "activity_type_id", "status", "effective_from"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("ALTER TABLE activity_types DROP CONSTRAINT ck_activity_types_quantity_unit_valid")
    op.execute(
        "ALTER TABLE activity_types ADD CONSTRAINT ck_activity_types_quantity_unit_valid "
        "CHECK (quantity_unit IN ('head', 'ton', 'hive', 'ha', 'person_day', 'm3', 'unit'))"
    )

    op.execute(
        "ALTER TABLE rule_parameters ADD CONSTRAINT ex_rule_parameters_one_in_force "
        "EXCLUDE USING gist (code WITH =, "
        "daterange(effective_from, effective_to, '[]') WITH &&) "
        "WHERE (status = 'published')"
    )
    op.execute(
        "ALTER TABLE tariffs ADD CONSTRAINT ex_tariffs_one_in_force "
        "EXCLUDE USING gist (activity_type_id WITH =, "
        "COALESCE(livestock_group, '') WITH =, "
        "daterange(effective_from, effective_to, '[]') WITH &&) "
        "WHERE (status = 'published')"
    )
    op.execute(
        "ALTER TABLE norms ADD CONSTRAINT ex_norms_one_in_force "
        "EXCLUDE USING gist (contour_id WITH =, activity_type_id WITH =, "
        "daterange(effective_from, effective_to, '[]') WITH &&) "
        "WHERE (status = 'published')"
    )

    op.execute(
        """
        CREATE FUNCTION calculations_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'calculations is append-only: a recalculation is a new row';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER calculations_append_only "
        "BEFORE UPDATE OR DELETE ON calculations "
        "FOR EACH ROW EXECUTE FUNCTION calculations_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER calculations_no_truncate "
        "BEFORE TRUNCATE ON calculations "
        "FOR EACH STATEMENT EXECUTE FUNCTION calculations_forbid_mutation()"
    )

    for role, codes in (
        ("gis_specialist", ("norms.manage",)),
        ("leadership", ("norms.approve", "norms.publish")),
        ("central_admin", ("norms.publish", "norms.tariffs.manage", "norms.tariffs.publish")),
    ):
        for code in codes:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :code FROM roles WHERE code = :role "
                    "ON CONFLICT DO NOTHING"
                ).bindparams(code=code, role=role)
            )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM role_permissions WHERE permission_code IN "
        "('norms.manage', 'norms.approve', 'norms.publish', "
        " 'norms.tariffs.manage', 'norms.tariffs.publish')"
    )
    op.execute("DROP TRIGGER IF EXISTS calculations_no_truncate ON calculations")
    op.execute("DROP TRIGGER IF EXISTS calculations_append_only ON calculations")
    op.execute("DROP FUNCTION IF EXISTS calculations_forbid_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_norms_lookup", table_name="norms")
    op.drop_table("norms")
    op.drop_index("ix_calculations_application", table_name="calculations")
    op.drop_table("calculations")
    op.drop_index("ix_tariffs_lookup", table_name="tariffs")
    op.drop_table("tariffs")
    op.drop_index("ix_rule_parameters_lookup", table_name="rule_parameters")
    op.drop_table("rule_parameters")
    # ### end Alembic commands ###

    # A downgrade must delete the rows its upgrade made legal (lesson) — belt-and-
    # braces for a database where 0012 never ran; see the module docstring's note
    # on ordering relative to 0012's own downgrade.
    op.execute("ALTER TABLE activity_types DROP CONSTRAINT ck_activity_types_quantity_unit_valid")
    op.execute(
        "ALTER TABLE activity_types ADD CONSTRAINT ck_activity_types_quantity_unit_valid "
        "CHECK (quantity_unit IN ('head', 'ton', 'hive', 'ha', 'person', 'unit'))"
    )
    op.execute(
        "UPDATE activity_types SET quantity_unit = 'ton' WHERE code IN ('haymaking', 'deadwood')"
    )
    op.execute("UPDATE activity_types SET quantity_unit = 'ha' WHERE code IN ('recreation')")
