"""signatures

Adds certificates (bound ERI certificates) and signatures (document signatures)
(design/02 § signatures, plan 03.8). `certificates` is identity — one row per
(serial_number, issuer) pair, owned by at most one user (`uq_certificate_identity`).
`signatures` is evidence, never updated: a partial unique index allows at most one
`valid` signature per (object_type, object_id, purpose) — a second valid attempt is
refused (ERR-SIGN-002) while an invalid attempt is still written and does not occupy
the slot (ruling 8).

No role is granted the module's `signatures.view_any` / `signatures.reverify` codes
here: the approved plan (rulings 1-12) does not name one, and `signatures.view_any`
is explicitly scoped to oversight (stage 4.2), which does not exist yet. Both codes
are registered in `app.modules.auth.permissions` regardless (import-time, not this
migration), so `require_permission` already resolves them; with no `role_permissions`
row, only `sys_admin` (a superuser that bypasses the check entirely, decision #41
ruling 2) can currently exercise them — a safe, inert default until a role decision
is made and grants them via an additive migration.

Revision ID: 0014
Revises: 0010
Create Date: 2026-09-01 19:23:25.575563

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("serial_number", sa.Text(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("pinfl_or_stir", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "bound_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')", name=op.f("ck_certificates_status_valid")
        ),
        sa.CheckConstraint("valid_to > valid_from", name=op.f("ck_certificates_validity_ordered")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_certificates_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("serial_number", "issuer", name="uq_certificate_identity"),
    )
    op.create_table(
        "signatures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("signer_user_id", sa.Uuid(), nullable=True),
        sa.Column("certificate_id", sa.Uuid(), nullable=False),
        sa.Column("doc_hash", sa.Text(), nullable=False),
        sa.Column("signature_value", sa.Text(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "verification_status IN ('valid', 'invalid')",
            name=op.f("ck_signatures_verification_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_signatures_certificate_id_certificates"),
        ),
        sa.ForeignKeyConstraint(
            ["signer_user_id"], ["users.id"], name=op.f("fk_signatures_signer_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signatures")),
    )
    op.create_index(
        "ix_signatures_object", "signatures", ["object_type", "object_id"], unique=False
    )
    op.create_index(
        "uq_signatures_valid_purpose",
        "signatures",
        ["object_type", "object_id", "purpose"],
        unique=True,
        postgresql_where=sa.text("verification_status = 'valid'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # No seed rows were inserted by upgrade() (no role grants — see module docstring),
    # so there is nothing to delete before dropping the tables (lesson: a downgrade
    # must delete the rows its upgrade made legal — none exist here).

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_signatures_valid_purpose",
        table_name="signatures",
        postgresql_where=sa.text("verification_status = 'valid'"),
    )
    op.drop_index("ix_signatures_object", table_name="signatures")
    op.drop_table("signatures")
    op.drop_table("certificates")
    # ### end Alembic commands ###
