"""signatures

Adds certificates (bound ERI certificates) and signatures (document signatures)
(design/02 § signatures, plan 03.8). `certificates` is identity — one row per
(serial_number, issuer) pair, owned by at most one user (`uq_certificate_identity`).
`signatures` is evidence, never updated: a partial unique index allows at most one
`valid` signature per (object_type, object_id, purpose) — a second valid attempt is
refused (ERR-SIGN-002) while an invalid attempt is still written and does not occupy
the slot (ruling 8).

Grants `signatures.view_any` to `prosecutor` and `central_admin`, and
`signatures.reverify` to `central_admin` only (post-plan ruling: the approved plan,
rulings 1-12, named no role, so Task 1 registered both codes with no grant and
flagged the gap; this closes it). `sys_admin` gets no row — it bypasses
`require_permission` before codes are checked (decision #41 ruling 2), so an
explicit grant would be redundant.

Revision ID: 0014
Revises: 0013
Create Date: 2026-09-01 19:23:25.575563

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0014"
down_revision: str | Sequence[str] | None = "0013"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# prosecutor is deliberately excluded from reverify: design/01 rule 5 makes oversight
# a reader, and tz/03 keeps the prosecutor read-only at the API level, while reverify
# writes a new signature row — do not "fix" this asymmetry.
ROLE_GRANTS: list[tuple[str, str]] = [
    ("prosecutor", "signatures.view_any"),
    ("central_admin", "signatures.view_any"),
    ("central_admin", "signatures.reverify"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("serial_number", sa.Text(), nullable=False),
        sa.Column("issuer", sa.Text(), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("pinfl_or_stir", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "bound_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unbound_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('active', 'revoked', 'expired')", name=op.f("ck_certificates_status_valid")
        ),
        sa.CheckConstraint("valid_to > valid_from", name=op.f("ck_certificates_validity_ordered")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_certificates_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificates")),
        sa.UniqueConstraint("serial_number", "issuer", name="uq_certificate_identity"),
    )
    op.create_table(
        "signatures",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("purpose", sa.Text(), nullable=False),
        sa.Column("signer_user_id", sa.Uuid(), nullable=True),
        sa.Column("certificate_id", sa.Uuid(), nullable=False),
        sa.Column("doc_hash", sa.Text(), nullable=False),
        sa.Column("signature_value", sa.Text(), nullable=False),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verification", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verification_status", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "verification_status IN ('valid', 'invalid')",
            name=op.f("ck_signatures_verification_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["certificate_id"],
            ["certificates.id"],
            name=op.f("fk_signatures_certificate_id_certificates"),
        ),
        sa.ForeignKeyConstraint(
            ["signer_user_id"], ["users.id"], name=op.f("fk_signatures_signer_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signatures")),
    )
    op.create_index(
        "ix_signatures_object", "signatures", ["object_type", "object_id"], unique=False
    )
    op.create_index(
        "uq_signatures_valid_purpose",
        "signatures",
        ["object_type", "object_id", "purpose"],
        unique=True,
        postgresql_where=sa.text("verification_status = 'valid'"),
    )
    # ### end Alembic commands ###
    for role_code, permission_code in ROLE_GRANTS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_code)"
                " SELECT id, :perm FROM roles WHERE code = :role"
                " ON CONFLICT DO NOTHING"
            ).bindparams(perm=permission_code, role=role_code)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeds — a downgrade must delete the rows its upgrade made legal (lesson).
    op.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_code IN"
            " ('signatures.view_any', 'signatures.reverify')"
        )
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_signatures_valid_purpose",
        table_name="signatures",
        postgresql_where=sa.text("verification_status = 'valid'"),
    )
    op.drop_index("ix_signatures_object", table_name="signatures")
    op.drop_table("signatures")
    op.drop_table("certificates")
    # ### end Alembic commands ###
