"""applications

Schema for stage 3.9a (design/02 § applications, corrected by plan
03.9a-applications-core): the eight tables the module hangs off, plus
`number_counters` in `core`. `applications.status` carries all 14 tz/05 statuses
and `application_checks.check_type` the eleven values of ruling 21 from day one,
even though this stage only writes a subset of each (see the plan). Two invariants
SQLAlchemy cannot express and Alembic does not diff: the partial GiST EXCLUDE
constraint forbidding two active applications for the same (applicant, contour,
activity) on an overlapping period (`ex_applications_no_duplicate`, ruling 6;
btree_gist already installed by 0001), and the append-only trigger on
`application_status_history`, mirroring `audit_log`'s (0002) and `calculations`'s
(0011) own. Also closes `calculations.application_id`'s deferred FK — `NOT VALID`
then `VALIDATE CONSTRAINT`, the same way 0003 closed `audit_log.user_id` — now that
`applications` exists (ruling from the controller's review). Grants the five new
permission codes (ruling 16) to applicant/executor_staff/leadership/prosecutor/
sys_admin. Seeds no notification templates: 0009 already seeds
`application.submitted`/`.approved`/`.rejected`, and this branch calls `notify()`
nowhere.

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-02 04:53:39.609205

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: str | Sequence[str] | None = "0014"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# ruling 16: hodim is tz/03 role `executor_staff`, not a real roles.code value —
# resolved here, not left as the plan's own prose (.claude/lessons.md: "the rahbar's
# role code is leadership, not rahbar").
ROLE_GRANTS: list[tuple[str, str]] = [
    ("applicant", "applications.create"),
    ("executor_staff", "applications.review"),
    ("leadership", "applications.decide"),
    ("prosecutor", "applications.view_any"),
    ("sys_admin", "applications.assign"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "number_counters",
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("last_value", sa.BigInteger(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("scope", name=op.f("pk_number_counters")),
    )
    op.create_table(
        "applications",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Text(), nullable=True),
        sa.Column("applicant_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("on_behalf", sa.Text(), nullable=False),
        sa.Column("representation_id", sa.Uuid(), nullable=True),
        sa.Column("activity_type_id", sa.Uuid(), nullable=True),
        sa.Column("contour_id", sa.Uuid(), nullable=True),
        sa.Column("contour_version_id", sa.Uuid(), nullable=True),
        sa.Column("requested_area_ha", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("period_from", sa.Date(), nullable=True),
        sa.Column("period_to", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("channel", sa.Text(), nullable=False),
        sa.Column("mygov_reference", sa.Text(), nullable=True),
        sa.Column("sla_deadline_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_org_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_user_id", sa.Uuid(), nullable=True),
        sa.Column("parent_application_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("rejection_reason_item_id", sa.Uuid(), nullable=True),
        sa.Column("benefit_category_item_id", sa.Uuid(), nullable=True),
        sa.Column("decision_basis", sa.Text(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "channel IN ('portal', 'mygov')", name=op.f("ck_applications_channel_valid")
        ),
        sa.CheckConstraint("kind IN ('new', 'extension')", name=op.f("ck_applications_kind_valid")),
        sa.CheckConstraint(
            "on_behalf IN ('self', 'legal')", name=op.f("ck_applications_on_behalf_valid")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'PENDING_INFO', 'RETURNED', "
            "'APPROVED', 'INVOICED', 'PAID', 'PERMIT_ISSUED', 'REJECTED', 'CANCELLED', "
            "'EXPIRED_UNPAID', 'CLOSED', 'ARCHIVED')",
            name=op.f("ck_applications_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["activity_type_id"],
            ["activity_types.id"],
            name=op.f("fk_applications_activity_type_id_activity_types"),
        ),
        sa.ForeignKeyConstraint(
            ["applicant_id"],
            ["applicants.id"],
            name=op.f("fk_applications_applicant_id_applicants"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_org_id"],
            ["organizations.id"],
            name=op.f("fk_applications_assigned_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_user_id"], ["users.id"], name=op.f("fk_applications_assigned_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["benefit_category_item_id"],
            ["classifier_items.id"],
            name=op.f("fk_applications_benefit_category_item_id_classifier_items"),
        ),
        sa.ForeignKeyConstraint(
            ["contour_id"], ["contours.id"], name=op.f("fk_applications_contour_id_contours")
        ),
        sa.ForeignKeyConstraint(
            ["contour_version_id"],
            ["contour_versions.id"],
            name=op.f("fk_applications_contour_version_id_contour_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_application_id"],
            ["applications.id"],
            name=op.f("fk_applications_parent_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["rejection_reason_item_id"],
            ["classifier_items.id"],
            name=op.f("fk_applications_rejection_reason_item_id_classifier_items"),
        ),
        sa.ForeignKeyConstraint(
            ["representation_id"],
            ["representations.id"],
            name=op.f("fk_applications_representation_id_representations"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_id"],
            ["users.id"],
            name=op.f("fk_applications_submitted_by_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("mygov_reference", name=op.f("uq_applications_mygov_reference")),
        sa.UniqueConstraint("number", name=op.f("uq_applications_number")),
    )
    op.create_index(
        op.f("ix_applications_activity_type_id"), "applications", ["activity_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_applicant_id"), "applications", ["applicant_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_assigned_org_id"), "applications", ["assigned_org_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_assigned_user_id"), "applications", ["assigned_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_benefit_category_item_id"),
        "applications",
        ["benefit_category_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_contour_id"), "applications", ["contour_id"], unique=False
    )
    op.create_index(
        op.f("ix_applications_contour_version_id"),
        "applications",
        ["contour_version_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_parent_application_id"),
        "applications",
        ["parent_application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_rejection_reason_item_id"),
        "applications",
        ["rejection_reason_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_representation_id"),
        "applications",
        ["representation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_applications_submitted_by_user_id"),
        "applications",
        ["submitted_by_user_id"],
        unique=False,
    )
    op.create_table(
        "application_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("org_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_by", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reason IN ('auto', 'absence', 'manual')",
            name=op.f("ck_application_assignments_reason_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_assignments_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"], ["users.id"], name=op.f("fk_application_assignments_assigned_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["org_id"],
            ["organizations.id"],
            name=op.f("fk_application_assignments_org_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_application_assignments_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_assignments")),
    )
    op.create_index(
        op.f("ix_application_assignments_application_id"),
        "application_assignments",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_assignments_assigned_by"),
        "application_assignments",
        ["assigned_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_assignments_org_id"),
        "application_assignments",
        ["org_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_assignments_user_id"),
        "application_assignments",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "uq_application_assignments_active",
        "application_assignments",
        ["application_id"],
        unique=True,
        postgresql_where=sa.text("is_active"),
    )
    op.create_table(
        "application_checks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("check_type", sa.Text(), nullable=False),
        sa.Column("result", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("doc_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "checked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "check_type IN ('gis_validity', 'gis_within_fund', 'gis_overlap', 'norm_available', "
            "'norm_season', 'norm_rotation', 'norm_fire_ban', 'norm_restrictions', 'norm_limit', "
            "'vet', 'cadastre')",
            name=op.f("ck_application_checks_check_type_valid"),
        ),
        sa.CheckConstraint(
            "result IN ('pass', 'fail', 'warning')", name=op.f("ck_application_checks_result_valid")
        ),
        sa.CheckConstraint(
            "source IN ('auto', 'external_api', 'manual_fallback')",
            name=op.f("ck_application_checks_source_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_checks_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["doc_file_id"],
            ["media_files.id"],
            name=op.f("fk_application_checks_doc_file_id_media_files"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_checks")),
    )
    op.create_index(
        op.f("ix_application_checks_application_id"),
        "application_checks",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_checks_doc_file_id"),
        "application_checks",
        ["doc_file_id"],
        unique=False,
    )
    op.create_table(
        "application_conclusions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('executor', 'gis')", name=op.f("ck_application_conclusions_kind_valid")
        ),
        sa.CheckConstraint(
            "recommendation IS NULL OR recommendation IN ('approve', 'reject')",
            name=op.f("ck_application_conclusions_recommendation_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_conclusions_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["author_id"], ["users.id"], name=op.f("fk_application_conclusions_author_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_conclusions")),
    )
    op.create_index(
        op.f("ix_application_conclusions_application_id"),
        "application_conclusions",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_conclusions_author_id"),
        "application_conclusions",
        ["author_id"],
        unique=False,
    )
    op.create_table(
        "application_documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("doc_type_item_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("uploaded_by", sa.Uuid(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_documents_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["doc_type_item_id"],
            ["classifier_items.id"],
            name=op.f("fk_application_documents_doc_type_item_id_classifier_items"),
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["media_files.id"],
            name=op.f("fk_application_documents_file_id_media_files"),
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"], ["users.id"], name=op.f("fk_application_documents_uploaded_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_documents")),
    )
    op.create_index(
        op.f("ix_application_documents_application_id"),
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_doc_type_item_id"),
        "application_documents",
        ["doc_type_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_documents_file_id"), "application_documents", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_application_documents_uploaded_by"),
        "application_documents",
        ["uploaded_by"],
        unique=False,
    )
    op.create_table(
        "application_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("livestock_type_id", sa.Uuid(), nullable=False),
        sa.Column("head_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("head_count > 0", name=op.f("ck_application_items_head_count_positive")),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_items_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["livestock_type_id"],
            ["livestock_types.id"],
            name=op.f("fk_application_items_livestock_type_id_livestock_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_items")),
        sa.UniqueConstraint(
            "application_id", "livestock_type_id", name="uq_application_items_livestock"
        ),
    )
    op.create_index(
        op.f("ix_application_items_application_id"),
        "application_items",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_items_livestock_type_id"),
        "application_items",
        ["livestock_type_id"],
        unique=False,
    )
    op.create_table(
        "application_status_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("from_status", sa.Text(), nullable=True),
        sa.Column("to_status", sa.Text(), nullable=False),
        sa.Column("changed_by", sa.Uuid(), nullable=True),
        sa.Column("reason_item_id", sa.Uuid(), nullable=True),
        sa.Column("reason_text", sa.Text(), nullable=True),
        sa.Column("legal_basis", sa.Text(), nullable=True),
        sa.Column("fields_to_fix", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IS NULL OR from_status IN ('DRAFT', 'SUBMITTED', 'IN_REVIEW', "
            "'PENDING_INFO', 'RETURNED', 'APPROVED', 'INVOICED', 'PAID', 'PERMIT_ISSUED', "
            "'REJECTED', 'CANCELLED', 'EXPIRED_UNPAID', 'CLOSED', 'ARCHIVED')",
            name=op.f("ck_application_status_history_from_status_valid"),
        ),
        sa.CheckConstraint(
            "to_status IN ('DRAFT', 'SUBMITTED', 'IN_REVIEW', 'PENDING_INFO', 'RETURNED', "
            "'APPROVED', 'INVOICED', 'PAID', 'PERMIT_ISSUED', 'REJECTED', 'CANCELLED', "
            "'EXPIRED_UNPAID', 'CLOSED', 'ARCHIVED')",
            name=op.f("ck_application_status_history_to_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_status_history_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_application_status_history_changed_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["reason_item_id"],
            ["classifier_items.id"],
            name=op.f("fk_application_status_history_reason_item_id_classifier_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_status_history")),
    )
    op.create_index(
        op.f("ix_application_status_history_application_id"),
        "application_status_history",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_status_history_changed_by"),
        "application_status_history",
        ["changed_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_application_status_history_reason_item_id"),
        "application_status_history",
        ["reason_item_id"],
        unique=False,
    )
    op.create_index(
        "ix_application_status_history_timeline",
        "application_status_history",
        ["application_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "info_requests",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("requested_by", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("response_text", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_info_requests_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["requested_by"], ["users.id"], name=op.f("fk_info_requests_requested_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_info_requests")),
    )
    op.create_index(
        op.f("ix_info_requests_application_id"), "info_requests", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_info_requests_requested_by"), "info_requests", ["requested_by"], unique=False
    )
    # ### end Alembic commands ###

    # The duplicate-application detector (ruling 6) — SQLAlchemy cannot express
    # EXCLUDE, so it is hand-written here. DRAFT sits outside the WHERE clause on
    # purpose: a duplicate is caught at submission, not while the applicant is
    # still typing. The service matches on this exact name.
    op.execute(
        "ALTER TABLE applications ADD CONSTRAINT ex_applications_no_duplicate "
        "EXCLUDE USING gist ("
        "applicant_id WITH =, contour_id WITH =, activity_type_id WITH =, "
        "daterange(period_from, period_to, '[]') WITH &&"
        ") WHERE (status IN ('SUBMITTED','IN_REVIEW','PENDING_INFO','RETURNED',"
        "'APPROVED','INVOICED','PAID','PERMIT_ISSUED') "
        "AND contour_id IS NOT NULL AND period_from IS NOT NULL AND period_to IS NOT NULL)"
    )

    # application_status_history is append-only, mirroring audit_log's (0002) and
    # calculations's (0011) own triggers exactly.
    op.execute(
        """
        CREATE FUNCTION application_status_history_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            RAISE EXCEPTION 'application_status_history is append-only: a correction is a new row';
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER application_status_history_append_only "
        "BEFORE UPDATE OR DELETE ON application_status_history "
        "FOR EACH ROW EXECUTE FUNCTION application_status_history_forbid_mutation()"
    )
    op.execute(
        "CREATE TRIGGER application_status_history_no_truncate "
        "BEFORE TRUNCATE ON application_status_history "
        "FOR EACH STATEMENT EXECUTE FUNCTION application_status_history_forbid_mutation()"
    )

    # Close norms' deferred FK (ruling from the controller's review of this plan):
    # `calculations.application_id` had no FK until `applications` existed. NOT
    # VALID first (the table already has rows), then VALIDATE — the same idiom
    # 0003 used to close audit_log.user_id.
    op.execute(
        "ALTER TABLE calculations ADD CONSTRAINT fk_calculations_application_id_applications "
        "FOREIGN KEY (application_id) REFERENCES applications (id) NOT VALID"
    )
    op.execute(
        "ALTER TABLE calculations VALIDATE CONSTRAINT fk_calculations_application_id_applications"
    )

    for role, code in ROLE_GRANTS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_code) "
                "SELECT id, :code FROM roles WHERE code = :role "
                "ON CONFLICT DO NOTHING"
            ).bindparams(code=code, role=role)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeds and added invariants — a downgrade must undo whatever its upgrade made
    # possible or legal (lesson), in reverse order.
    op.execute(
        "DELETE FROM role_permissions WHERE permission_code IN "
        "('applications.create', 'applications.review', 'applications.decide', "
        " 'applications.view_any', 'applications.assign')"
    )
    op.execute(
        "ALTER TABLE calculations DROP CONSTRAINT fk_calculations_application_id_applications"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS application_status_history_no_truncate "
        "ON application_status_history"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS application_status_history_append_only "
        "ON application_status_history"
    )
    op.execute("DROP FUNCTION IF EXISTS application_status_history_forbid_mutation()")
    op.execute("ALTER TABLE applications DROP CONSTRAINT IF EXISTS ex_applications_no_duplicate")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_info_requests_requested_by"), table_name="info_requests")
    op.drop_index(op.f("ix_info_requests_application_id"), table_name="info_requests")
    op.drop_table("info_requests")
    op.drop_index("ix_application_status_history_timeline", table_name="application_status_history")
    op.drop_index(
        op.f("ix_application_status_history_reason_item_id"),
        table_name="application_status_history",
    )
    op.drop_index(
        op.f("ix_application_status_history_changed_by"), table_name="application_status_history"
    )
    op.drop_index(
        op.f("ix_application_status_history_application_id"),
        table_name="application_status_history",
    )
    op.drop_table("application_status_history")
    op.drop_index(op.f("ix_application_items_livestock_type_id"), table_name="application_items")
    op.drop_index(op.f("ix_application_items_application_id"), table_name="application_items")
    op.drop_table("application_items")
    op.drop_index(op.f("ix_application_documents_uploaded_by"), table_name="application_documents")
    op.drop_index(op.f("ix_application_documents_file_id"), table_name="application_documents")
    op.drop_index(
        op.f("ix_application_documents_doc_type_item_id"), table_name="application_documents"
    )
    op.drop_index(
        op.f("ix_application_documents_application_id"), table_name="application_documents"
    )
    op.drop_table("application_documents")
    op.drop_index(
        op.f("ix_application_conclusions_author_id"), table_name="application_conclusions"
    )
    op.drop_index(
        op.f("ix_application_conclusions_application_id"), table_name="application_conclusions"
    )
    op.drop_table("application_conclusions")
    op.drop_index(op.f("ix_application_checks_doc_file_id"), table_name="application_checks")
    op.drop_index(op.f("ix_application_checks_application_id"), table_name="application_checks")
    op.drop_table("application_checks")
    op.drop_index(
        "uq_application_assignments_active",
        table_name="application_assignments",
        postgresql_where=sa.text("is_active"),
    )
    op.drop_index(op.f("ix_application_assignments_user_id"), table_name="application_assignments")
    op.drop_index(op.f("ix_application_assignments_org_id"), table_name="application_assignments")
    op.drop_index(
        op.f("ix_application_assignments_assigned_by"), table_name="application_assignments"
    )
    op.drop_index(
        op.f("ix_application_assignments_application_id"), table_name="application_assignments"
    )
    op.drop_table("application_assignments")
    op.drop_index(op.f("ix_applications_submitted_by_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_representation_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_rejection_reason_item_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_parent_application_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_contour_version_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_contour_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_benefit_category_item_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_assigned_user_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_assigned_org_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_applicant_id"), table_name="applications")
    op.drop_index(op.f("ix_applications_activity_type_id"), table_name="applications")
    op.drop_table("applications")
    op.drop_table("number_counters")
    # ### end Alembic commands ###
