"""payments

Schema for stage 3.10a task 1 (design/02 § payments, plan
`03.10a-payments-core`): the four tables the module hangs off —
`invoices`, `payment_intents`, `provider_transactions`, `allocations`. See
`app/modules/payments/models.py`'s own docstring for what each table holds and for
the two corrections against design/02 decided ahead of this task:

- **Ruling P1** — `provider_transactions.invoice_id` is a NOT NULL FK to
  `invoices.id`, not the sole `intent_id null` design/02 lists (Payme's
  `PerformTransaction` may have no `payment_intents` row of ours to point at).
  `intent_id` stays as a nullable FK beside it.
- **Ruling P2** — `allocations.refund_id` is omitted: its target, `refunds`, is a
  3.10b table that does not exist yet, and a nullable FK to a non-existent table
  is not expressible. 3.10b adds the column with its FK when it creates `refunds`.

The five tables design/02 also lists under § payments
(`manual_payment_confirmations`, `bank_statements`, `bank_statement_lines`,
`reconciliations`, `refunds`) are 3.10b's, not this migration's.

Both invariant-carrying constraints are plain SQLAlchemy metadata, unlike
applications' hand-written EXCLUDE (0015) — autogenerate saw them on its own and
they need no `op.execute`: `uq_invoices_one_in_force` (ruling 10, a partial unique
index — at most one `pending`/`paid` invoice per application at a time) and
`uq_provider_transactions_external` (ruling 5 — Payme's verbatim retry of a call it
never got an answer to must not create a second transaction).

Task 2 amends this migration in place (still this branch's own, not yet merged
anywhere, so no separate revision is burned for one column): `invoices.calculation_id`,
a nullable FK to `calculations.id` — `payments.service.issue_invoice` freezes which
calculation it billed, and design/02 never listed the column at all.

Task 3 amends it again, same reasoning: `allocations.account` becomes nullable.
The state budget's account number is not in the system at all (`tz/08` — settled
by accounting outside the system), and a leshoz's `requisites` JSONB may
legitimately have no `"account"` key — a placeholder string in a financial
ledger's account column would be worse than NULL. See
`app/modules/payments/models.py`'s `Allocation` docstring.

Task 4 amends it a third time (ruling A): `provider_transactions.performed_at`
loses both its `NOT NULL` and its `server_default=now()` — a transaction sitting
in state `1` must report `perform_time: 0` to Payme's `CheckTransaction`, not the
moment the row was created — and gains two siblings design/02 lists neither of,
`cancelled_at` (nullable timestamptz) and `cancel_reason` (nullable integer,
design/04 §3.5's reasons 1-5/10). See
`app/modules/payments/models.py`'s `ProviderTransaction` docstring.

Grants the two new permission codes (`payments.view`, `payments.manage`) to
`accountant` (`roles.code = 'accountant'`, «Бухгалтер» — seeded by 0003_auth.py;
verified against that migration, not plan prose, per the lesson on role codes).
`sys_admin` needs no explicit grant: it is a superuser and `require_permission`
lets it through before checking codes (decision #41 ruling 2).

Revision ID: 0017
Revises: 0016
Create Date: 2026-09-02 13:14:05.329788

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0017"
down_revision: str | Sequence[str] | None = "0016"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

ROLE_GRANTS: list[tuple[str, str]] = [
    ("accountant", "payments.view"),
    ("accountant", "payments.manage"),
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.Text(), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("calculation_id", sa.Uuid(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column(
            "issued_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "due_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'paid', 'expired', 'cancelled')",
            name=op.f("ck_invoices_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_invoices_application_id_applications"),
        ),
        sa.ForeignKeyConstraint(
            ["calculation_id"],
            ["calculations.id"],
            name=op.f("fk_invoices_calculation_id_calculations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("number", name=op.f("uq_invoices_number")),
    )
    op.create_index(
        op.f("ix_invoices_application_id"), "invoices", ["application_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_calculation_id"), "invoices", ["calculation_id"], unique=False
    )
    op.create_index(
        "uq_invoices_one_in_force",
        "invoices",
        ["application_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('pending', 'paid')"),
    )
    op.create_table(
        "payment_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("external_ref", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('payme', 'manual')", name=op.f("ck_payment_intents_provider_valid")
        ),
        sa.CheckConstraint(
            "status IN ('created', 'pending', 'succeeded', 'failed', 'expired')",
            name=op.f("ck_payment_intents_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_payment_intents_invoice_id_invoices")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payment_intents")),
    )
    op.create_index(
        op.f("ix_payment_intents_invoice_id"), "payment_intents", ["invoice_id"], unique=False
    )
    op.create_table(
        "provider_transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("intent_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("state", sa.Text(), nullable=False),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["intent_id"],
            ["payment_intents.id"],
            name=op.f("fk_provider_transactions_intent_id_payment_intents"),
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
            name=op.f("fk_provider_transactions_invoice_id_invoices"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_transactions")),
        sa.UniqueConstraint("provider", "external_id", name="uq_provider_transactions_external"),
    )
    op.create_index(
        op.f("ix_provider_transactions_intent_id"),
        "provider_transactions",
        ["intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_provider_transactions_invoice_id"),
        "provider_transactions",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "allocations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("invoice_id", sa.Uuid(), nullable=False),
        sa.Column("transaction_id", sa.Uuid(), nullable=True),
        sa.Column("entry_type", sa.Text(), nullable=False),
        sa.Column("target", sa.Text(), nullable=False),
        sa.Column("account", sa.Text(), nullable=True),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "entry_type IN ('payment', 'refund', 'correction')",
            name=op.f("ck_allocations_entry_type_valid"),
        ),
        sa.CheckConstraint(
            "target IN ('recipient', 'budget', 'other')", name=op.f("ck_allocations_target_valid")
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"], ["invoices.id"], name=op.f("fk_allocations_invoice_id_invoices")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["provider_transactions.id"],
            name=op.f("fk_allocations_transaction_id_provider_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    op.create_index(op.f("ix_allocations_invoice_id"), "allocations", ["invoice_id"], unique=False)
    op.create_index(
        op.f("ix_allocations_transaction_id"), "allocations", ["transaction_id"], unique=False
    )
    # ### end Alembic commands ###

    for role, code in ROLE_GRANTS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_code) "
                "SELECT id, :code FROM roles WHERE code = :role "
                "ON CONFLICT DO NOTHING"
            ).bindparams(code=code, role=role)
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Seeded grants — a downgrade must undo whatever its upgrade made possible or
    # legal (lesson), in reverse order.
    op.execute(
        "DELETE FROM role_permissions WHERE permission_code IN ('payments.view', 'payments.manage')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_allocations_transaction_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_invoice_id"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_provider_transactions_invoice_id"), table_name="provider_transactions")
    op.drop_index(op.f("ix_provider_transactions_intent_id"), table_name="provider_transactions")
    op.drop_table("provider_transactions")
    op.drop_index(op.f("ix_payment_intents_invoice_id"), table_name="payment_intents")
    op.drop_table("payment_intents")
    op.drop_index(
        "uq_invoices_one_in_force",
        table_name="invoices",
        postgresql_where=sa.text("status IN ('pending', 'paid')"),
    )
    op.drop_index(op.f("ix_invoices_calculation_id"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_application_id"), table_name="invoices")
    op.drop_table("invoices")
    # ### end Alembic commands ###
