"""reports

Revision ID: 0027
Revises: 0023
Create Date: 2026-09-06 01:22:42.509473

Plan `04.3-reports` task 1: `report_forms` (the form builder) and `reports`
(one submitted report per form/organization/period/version), design/02 §
reports. `down_revision = "0023"`, the head at the time this branch forked —
**this is NOT the merge order**: 04-06-parallel-run.md has four sibling
tracks each claiming `0023` as parent while working alone, and whichever
merges first keeps it; every later one re-points its own `down_revision`
(and `tests/test_migrations.py`'s head literal, same commit) onto the new
head before opening its PR. This branch is not merging — see the track
report.

Ruling 1 (plan header): an APPROVED report is frozen at the database level,
the `audit_log`/`calculations` append-only shape applied conditionally
(`OLD.status = 'approved'` only, not every row unconditionally) — a
correction after approval is a NEW row (`version_no + 1`), never an edit in
place.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0027"
down_revision: str | Sequence[str] | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# (role_code, permission_code) — tz/03's 4-ilova matrix row "Отчёты", verbatim
# (plan ruling 2): `sys_admin` is omitted on purpose (decision #41 ruling 2
# already waves it through every `require_permission` gate, so a seeded grant
# would be redundant, not additive) and `inspector`/`applicant` are omitted
# because the matrix marks them "—" for this object.
ROLE_GRANTS: list[tuple[str, str]] = [
    ("central_admin", "reports.view"),
    ("leadership", "reports.view"),
    ("executor_staff", "reports.view"),
    ("gis_specialist", "reports.view"),
    ("executor_head", "reports.view"),
    ("accountant", "reports.view"),
    ("prosecutor", "reports.view"),
    ("central_admin", "reports.manage"),
    ("executor_staff", "reports.manage"),
    ("accountant", "reports.manage"),
    ("executor_head", "reports.sign"),
    ("central_admin", "reports.accept"),
    ("central_admin", "reports.forms.manage"),
]

_GRANTED_CODES = sorted({code for _, code in ROLE_GRANTS})


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_forms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("name", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("activity_type_id", sa.Uuid(), nullable=True),
        sa.Column("period_type", sa.Text(), nullable=False),
        sa.Column("columns", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "period_type IN ('month', 'quarter', 'year')",
            name=op.f("ck_report_forms_period_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'active', 'archived')", name=op.f("ck_report_forms_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["activity_type_id"],
            ["activity_types.id"],
            name=op.f("fk_report_forms_activity_type_id_activity_types"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_report_forms_created_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_forms")),
        sa.UniqueConstraint("code", "version", name="uq_report_forms_code_version"),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("form_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("parent_report_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("returned_by", sa.Text(), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("filled_by", sa.Uuid(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("returned_comment", sa.Text(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "returned_by IS NULL OR returned_by IN ('head', 'center')",
            name=op.f("ck_reports_returned_by_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('created', 'submitted', 'head_approved', 'returned', 'approved')",
            name=op.f("ck_reports_status_valid"),
        ),
        sa.CheckConstraint("period_end >= period_start", name=op.f("ck_reports_period_ordered")),
        sa.ForeignKeyConstraint(
            ["approved_by"], ["users.id"], name=op.f("fk_reports_approved_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_reports_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["filled_by"], ["users.id"], name=op.f("fk_reports_filled_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["form_id"], ["report_forms.id"], name=op.f("fk_reports_form_id_report_forms")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_report_id"], ["reports.id"], name=op.f("fk_reports_parent_report_id_reports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint(
            "form_id",
            "organization_id",
            "period_start",
            "version_no",
            name="uq_reports_form_org_period_version",
        ),
    )
    op.create_index(op.f("ix_reports_form_id"), "reports", ["form_id"], unique=False)
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    # A hodim's own worklist reads "my organization's reports by status" —
    # the single-column FK index above does not serve that predicate.
    op.create_index(
        "ix_reports_organization_status", "reports", ["organization_id", "status"], unique=False
    )
    # ### end Alembic commands ###

    # Plan ruling 1 / module docstring: freeze an APPROVED report at the
    # database level, the same "this row now IS the record" shape audit_log
    # (migration 0002) and calculations (migration 0011) already use —
    # conditioned on OLD.status so the row stays mutable through
    # created/submitted/head_approved/returned.
    op.execute(
        """
        CREATE FUNCTION reports_forbid_mutation() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
            IF OLD.status = 'approved' THEN
                RAISE EXCEPTION 'an approved report is frozen; create a new version instead';
            END IF;
            RETURN NEW;
        END;
        $$
        """
    )
    op.execute(
        "CREATE TRIGGER reports_freeze_approved "
        "BEFORE UPDATE ON reports "
        "FOR EACH ROW EXECUTE FUNCTION reports_forbid_mutation()"
    )

    for role_code, permission_code in ROLE_GRANTS:
        op.execute(
            sa.text(
                "INSERT INTO role_permissions (role_id, permission_code)"
                " SELECT id, :perm FROM roles WHERE code = :role"
                " ON CONFLICT DO NOTHING"
            ).bindparams(perm=permission_code, role=role_code)
        )


def downgrade() -> None:
    """Downgrade schema."""
    codes_list = ", ".join(f"'{code}'" for code in _GRANTED_CODES)
    op.execute(f"DELETE FROM role_permissions WHERE permission_code IN ({codes_list})")

    op.execute("DROP TRIGGER IF EXISTS reports_freeze_approved ON reports")
    op.execute("DROP FUNCTION IF EXISTS reports_forbid_mutation()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_reports_organization_status", table_name="reports")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_form_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("report_forms")
    # ### end Alembic commands ###
