"""search_archive

Track B4 of the stage 4+6 parallel fleet (`docs/plans/04-06-parallel-run.md`,
`docs/plans/04.5-4.7-search-archive.md`): two new tables for two narrow reader
modules, `search` and `archive`. Neither table adds a column to, or an index
on, any table another module owns — plan ruling 1 explains why `search`'s
full-text is live `ILIKE`/`similarity()` rather than a persisted tsvector
column on `applications`/`applicants`/`permits`, which `design/02` §search
originally called for and this migration deliberately does not do (a reader
must never edit another module's models — `backend/CLAUDE.md`).

`saved_filters` — a user's own saved search profile (design/02 §search).
`archive_items` — one archived object, `organization_id` added beyond
`design/02`'s own column list (plan ruling 6) so `GET /archive` can be
zone-filtered directly, without joining back through a polymorphic
`object_type`/`object_id` pair into two different tables.

Role grants: `search.use` to the roles that already hold both domains' own
view permissions (`central_admin`, `leadership`, `executor_head`,
`executor_staff`, `prosecutor`); `archive.manage` to the two roles plausibly
doing archival housekeeping (`central_admin`, `executor_head`).

`0029` is this track's reserved revision number
(`docs/plans/04-06-parallel-run.md`). `down_revision` is `0023`, the head
this branch was cut from — **whoever merges first into `dev` keeps it; every
subsequent branch re-points its own `down_revision` onto the new head before
opening its PR** (the migration-number rule in that same file). This branch
does not merge itself, so this stays `0023` here.

Revision ID: 0029
Revises: 0023
Create Date: 2026-09-06 02:29:14.066285
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0029"
down_revision: str | Sequence[str] | None = "0023"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Same idiom as every other migration granting a fresh permission code
# (e.g. `0011_norms.py`): `role_permissions` is keyed on `(role_id,
# permission_code)` with no FK on the code itself — the registry lives in
# code (`auth.permissions.register`), the grant lives here.
_SEARCH_USE_ROLES = ("central_admin", "leadership", "executor_head", "executor_staff", "prosecutor")
_ARCHIVE_MANAGE_ROLES = ("central_admin", "executor_head")


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archive_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("object_type", sa.Text(), nullable=False),
        sa.Column("object_id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retention_until", sa.Date(), nullable=True),
        sa.Column("content_hash", sa.Text(), nullable=False),
        sa.Column("storage_ref", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "object_type IN ('application', 'permit')",
            name=op.f("ck_archive_items_object_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('stored', 'verified')", name=op.f("ck_archive_items_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_archive_items_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_archive_items_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_archive_items")),
        sa.UniqueConstraint("object_type", "object_id", name="uq_archive_items_object"),
    )
    op.create_index(
        op.f("ix_archive_items_created_by"), "archive_items", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_archive_items_object_id"), "archive_items", ["object_id"], unique=False
    )
    op.create_index(
        op.f("ix_archive_items_organization_id"),
        "archive_items",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "saved_filters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("shared", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('applications', 'permits')", name=op.f("ck_saved_filters_kind_valid")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_saved_filters_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_filters")),
        sa.UniqueConstraint("user_id", "name", name="uq_saved_filters_user_name"),
    )
    op.create_index(op.f("ix_saved_filters_user_id"), "saved_filters", ["user_id"], unique=False)
    # ### end Alembic commands ###

    for code, roles in (
        ("search.use", _SEARCH_USE_ROLES),
        ("archive.manage", _ARCHIVE_MANAGE_ROLES),
    ):
        for role in roles:
            op.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_code) "
                    "SELECT id, :code FROM roles WHERE code = :role "
                    "ON CONFLICT DO NOTHING"
                ).bindparams(code=code, role=role)
            )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(
        "DELETE FROM role_permissions WHERE permission_code IN ('search.use', 'archive.manage')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_filters_user_id"), table_name="saved_filters")
    op.drop_table("saved_filters")
    op.drop_index(op.f("ix_archive_items_organization_id"), table_name="archive_items")
    op.drop_index(op.f("ix_archive_items_object_id"), table_name="archive_items")
    op.drop_index(op.f("ix_archive_items_created_by"), table_name="archive_items")
    op.drop_table("archive_items")
    # ### end Alembic commands ###
