"""search exports

С22 (`docs/tz/12-otkrytye-voprosy.md` #42, decision #98, ruling #20): the
prosecutor's — and every other `search.use` holder's — watermarked PDF/XLSX
export of a `GET /search` result set, capped at a configurable row count
(`app/core/settings_store.py::search_export_max_rows`, default 10 000).

`export_jobs` lives beside `saved_filters` exactly where `design/02` always
put it, but this implementation is SYNCHRONOUS rather than the asynchronous
worker that document originally described — `app/modules/search/models.py`'s
own docstring on `ExportJob` justifies the table surviving that choice: it is
an export REGISTER (an operator's own history, each row re-downloadable
byte-for-byte), not a queue, so `status` only ever reaches a terminal value
('done'/'failed') within the same request that created the row.

No new permission: the four export routes reuse `search.use`, already
granted to `central_admin`, `leadership`, `executor_head`, `executor_staff`
and `prosecutor` by `0029_search_archive.py` — an export shows nothing a
search result page does not already, so a second code would only be a
second place for the two to drift apart. Decision #95 ("a module that adds a
read permission grants it to `prosecutor` in the same migration") is
therefore already satisfied and this migration grants nothing.

Revision ID: 0035
Revises: 0034
Create Date: 2026-09-07 02:12:07.133584

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0035"
down_revision: str | Sequence[str] | None = "0034"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "export_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("format", sa.Text(), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("status", sa.Text(), server_default="done", nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("total_matched", sa.Integer(), nullable=True),
        sa.Column("watermarked", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "finished_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "format IN ('pdf', 'xlsx')", name=op.f("ck_export_jobs_export_format_valid")
        ),
        sa.CheckConstraint(
            "kind IN ('applications', 'permits')", name=op.f("ck_export_jobs_export_kind_valid")
        ),
        sa.CheckConstraint(
            "status IN ('done', 'failed')", name=op.f("ck_export_jobs_export_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["file_id"], ["media_files.id"], name=op.f("fk_export_jobs_file_id_media_files")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_export_jobs_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_export_jobs")),
    )
    op.create_index(op.f("ix_export_jobs_user_id"), "export_jobs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_export_jobs_user_id"), table_name="export_jobs")
    op.drop_table("export_jobs")
    # ### end Alembic commands ###
