-- Schema app: applications and workflow. Specification module 10.1,
-- scenarios C3 through C8, state machine from appendix 5.
--
-- The core of the system. Three things here are load bearing:
--   * application_no_active_duplicate - the specification demands duplicate
--     control "by a constraint of the DBMS", with a KPI of zero duplicates
--     (clause 4.2.10, scenario C3 step 7). It is a constraint, not application
--     code, precisely because application code can be bypassed;
--   * calculation.rule_version and calculation.input_snapshot - the same input
--     must always produce the same result, and any calculation must remain
--     explainable years later (clauses 4.2.15 and 4.3.1);
--   * every status change is journalled in application_status_history. A
--     transition is never a bare UPDATE: it also writes history, an audit
--     record and an outbox message inside one transaction.
--
-- Column sets marked "verbatim" are transferred unchanged from
-- architecture/database.md in the documentation repository, sections 4.1, 5
-- and 7. Do not reformat them: they are the reviewed reference definitions.
--
-- Dependencies: extensions from 00-extensions.sql (postgis, btree_gist,
-- pgcrypto), schemas from 02-schemas.sql, tables from 20-iam, 30-geo, 40-rules.
-- Nothing here may reference permit or pay: those files are applied later.
-- Grants for oversight_ro are applied in 96-grants.sql, once tables exist.


-- ---------------------------------------------------------------------------
-- Registration number
-- ---------------------------------------------------------------------------

-- Numbers come from a sequence, never from MAX(number) + 1: under concurrent
-- submission the latter hands the same number to two applications.
-- The sequence is not gap free - a rolled back transaction consumes a value.
CREATE SEQUENCE app.application_number_seq;


-- ---------------------------------------------------------------------------
-- app.application
-- ---------------------------------------------------------------------------

CREATE TABLE app.application (
    id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    number            text NOT NULL UNIQUE,           -- A-00001, generated by a SEQUENCE
    applicant_id      uuid NOT NULL REFERENCES iam.applicant,
    organization_id   uuid NOT NULL REFERENCES iam.organization,
    territory_code    text NOT NULL,                  -- denormalised for ABAC and RLS
    activity_type     text NOT NULL,                  -- one of the 6 activity types
    contour_id        uuid REFERENCES geo.contour,
    geometry          geometry(MultiPolygon, 4326),
    area_ha           numeric(12,4),                  -- denormalised from geometry for speed
    quantity          jsonb,                          -- livestock by age group, beehives, hay volume (C3 step 4)
    period            daterange NOT NULL,
    status            text NOT NULL,
    channel           text NOT NULL,                  -- PORTAL | MYGOV
    assignee_id       uuid REFERENCES iam.user_account,
    submitted_at      timestamptz,                    -- registration moment, the SLA clock starts here
    sla_deadline      timestamptz,
    sla_paused_at     timestamptz,                    -- PENDING_INFO pauses the SLA timer
    reject_reason     text,                           -- RJ-01…RJ-15
    reject_legal_base text,
    reject_note       text,                           -- mandatory for RJ-15 (classifier 8.2)
    reject_fields     text[],                         -- fields the applicant must correct, set on RETURNED
    note              text,                           -- free text; carries unstructured legacy contour_info
    legacy_id         bigint,
    legacy_table      text,
    created_at        timestamptz NOT NULL DEFAULT now(),
    created_by        uuid,
    updated_at        timestamptz NOT NULL DEFAULT now(),
    updated_by        uuid
);

-- Wiring the sequence to the column keeps number generation in the database,
-- where the uniqueness guarantee already lives.
ALTER TABLE app.application
    ALTER COLUMN number
    SET DEFAULT 'A-' || lpad(nextval('app.application_number_seq')::text, 5, '0');

ALTER SEQUENCE app.application_number_seq OWNED BY app.application.number;

-- Enumerations are text plus CHECK, never enum types: an enum is painful to
-- change by migration, and this list is expected to grow (question O9 adds
-- hunting as a seventh activity type, question O10 adds a status before
-- SUBMITTED).
ALTER TABLE app.application
    -- 14 states from appendix 5, plus CONTRACT_DRAFT and REFUND_REQUESTED.
    -- Those two appear in appendix 5 only as transition targets and are never
    -- described as states - a documented gap in the specification, open
    -- questions P1 and P2. They are listed here because the exclusion
    -- constraint below treats CONTRACT_DRAFT as an active state; leaving them
    -- out would make that reference unreachable.
    ADD CONSTRAINT application_status_known CHECK (status IN (
        'DRAFT','SUBMITTED','IN_REVIEW','PENDING_INFO','RETURNED',
        'CONTRACT_DRAFT','APPROVED','INVOICED','PAID','REFUND_REQUESTED',
        'PERMIT_ISSUED','REJECTED','CANCELLED','EXPIRED_UNPAID','CLOSED',
        'ARCHIVED'
    )),

    -- The six kinds of use: grazing, haymaking, beehive placement, recreation
    -- and cultural use, firewood and deadwood collection, scientific research.
    ADD CONSTRAINT application_activity_type_known CHECK (activity_type IN (
        'GRAZING','HAYMAKING','BEEKEEPING','RECREATION','FIREWOOD','RESEARCH'
    )),

    ADD CONSTRAINT application_channel_known CHECK (channel IN ('PORTAL','MYGOV')),

    -- Rejection and return classifier, appendix 8.2.
    ADD CONSTRAINT application_reject_reason_known CHECK (reject_reason IS NULL OR reject_reason IN (
        'RJ-01','RJ-02','RJ-03','RJ-04','RJ-05','RJ-06','RJ-07','RJ-08',
        'RJ-09','RJ-10','RJ-11','RJ-12','RJ-13','RJ-14','RJ-15'
    )),

    -- A refusal without a classified reason cannot be appealed or explained.
    -- The legal base is required by the specification as well, but is not
    -- enforced here: legacy rows arrive as RJ-15 with the original free text
    -- and no legal base at all (see architecture/migration.md).
    ADD CONSTRAINT application_reject_reason_required CHECK (
        status NOT IN ('REJECTED','RETURNED') OR reject_reason IS NOT NULL
    ),

    -- RJ-15 is "other", and appendix 8.2 marks the note as mandatory for it.
    ADD CONSTRAINT application_reject_note_required CHECK (
        reject_reason <> 'RJ-15' OR reject_note IS NOT NULL
    ),

    -- Permits are issued for dates, so the period must be bounded on both
    -- sides and non-empty: an unbounded range would also defeat the overlap
    -- test in the exclusion constraint.
    ADD CONSTRAINT application_period_bounded CHECK (
        NOT isempty(period) AND lower(period) IS NOT NULL AND upper(period) IS NOT NULL
    ),

    -- PENDING_INFO is the only state that stops the SLA timer. Once the
    -- applicant answers, the pause mark is cleared and the elapsed time is
    -- added to sla_deadline.
    ADD CONSTRAINT application_sla_pause_only_pending CHECK (
        sla_paused_at IS NULL OR status = 'PENDING_INFO'
    ),

    ADD CONSTRAINT application_area_non_negative CHECK (area_ha IS NULL OR area_ha >= 0),

    -- Invalid geometry breaks every spatial check downstream, so it never
    -- gets stored. Error ERR-GIS-001.
    ADD CONSTRAINT application_geometry_valid CHECK (geometry IS NULL OR ST_IsValid(geometry));

-- One active application per applicant + contour + activity type + period.
-- Verbatim from architecture/database.md section 4.1. Verified on a live
-- PostgreSQL 18.1 on 10 August 2026: btree_gist accepts uuid in EXCLUDE, so no
-- fallback (casting applicant_id to text, or a composite hash) is needed.
-- A violation surfaces as HTTP 409 with code ERR-APP-002 and the number of the
-- existing application. Terminal states are absent from the predicate on
-- purpose: a rejected or cancelled application must not block a new one.
ALTER TABLE app.application
ADD CONSTRAINT application_no_active_duplicate
EXCLUDE USING gist (
    applicant_id   WITH =,
    contour_id     WITH =,
    activity_type  WITH =,
    period         WITH &&
)
WHERE (status IN (
    'SUBMITTED','IN_REVIEW','PENDING_INFO','CONTRACT_DRAFT',
    'APPROVED','INVOICED','PAID','PERMIT_ISSUED'
));

-- Indexes, verbatim from architecture/database.md section 7. Targets from
-- clause 4.1.4: p95 API under 500 ms with 1000 concurrent users.

-- executor worklist: territory + status + deadline
CREATE INDEX application_worklist ON app.application (territory_code, status, sla_deadline)
    WHERE status IN ('SUBMITTED','IN_REVIEW','PENDING_INFO');

-- applicant cabinet listing
CREATE INDEX application_by_applicant ON app.application (applicant_id, created_at DESC);

-- assigned to an executor
CREATE INDEX application_by_assignee ON app.application (assignee_id, status)
    WHERE assignee_id IS NOT NULL;

-- prosecutor filters, scenario C22, must answer within 3 seconds
CREATE INDEX application_prosecutor ON app.application (territory_code, created_at DESC, status);

-- Every geometry column carries a GiST index, section 6.
CREATE INDEX application_geom_gix ON app.application USING gist (geometry);


-- ---------------------------------------------------------------------------
-- app.application_status_history
-- ---------------------------------------------------------------------------

-- A journal, not an entity: rows are appended and never edited, so it carries
-- occurred_at and an actor instead of the usual four audit columns.
-- Appendix 5 requires every transition to record who, when, from which address
-- and device, and on what legal ground. This table is the workflow's own copy;
-- the system wide record goes to audit.audit_log in the same transaction.
CREATE TABLE app.application_status_history (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES app.application,
    from_status    text,                    -- NULL for the row that creates the application
    to_status      text NOT NULL,
    actor_id       uuid REFERENCES iam.user_account,   -- NULL when the system itself moves the application
    actor_role     text NOT NULL,           -- role in effect at that moment, kept even if the role is later changed
    reason         text,                    -- RJ-01…RJ-15 for rejection and return
    legal_base     text,
    note           text,
    ip             inet,
    device         text,
    correlation_id uuid,                    -- ties the transition to the audit record and the outbox message
    occurred_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE app.application_status_history
    ADD CONSTRAINT application_history_from_status_known CHECK (from_status IS NULL OR from_status IN (
        'DRAFT','SUBMITTED','IN_REVIEW','PENDING_INFO','RETURNED',
        'CONTRACT_DRAFT','APPROVED','INVOICED','PAID','REFUND_REQUESTED',
        'PERMIT_ISSUED','REJECTED','CANCELLED','EXPIRED_UNPAID','CLOSED',
        'ARCHIVED'
    )),
    ADD CONSTRAINT application_history_to_status_known CHECK (to_status IN (
        'DRAFT','SUBMITTED','IN_REVIEW','PENDING_INFO','RETURNED',
        'CONTRACT_DRAFT','APPROVED','INVOICED','PAID','REFUND_REQUESTED',
        'PERMIT_ISSUED','REJECTED','CANCELLED','EXPIRED_UNPAID','CLOSED',
        'ARCHIVED'
    )),
    ADD CONSTRAINT application_history_reason_known CHECK (reason IS NULL OR reason IN (
        'RJ-01','RJ-02','RJ-03','RJ-04','RJ-05','RJ-06','RJ-07','RJ-08',
        'RJ-09','RJ-10','RJ-11','RJ-12','RJ-13','RJ-14','RJ-15'
    )),
    -- A transition that changes nothing is a bug in the caller, not history.
    ADD CONSTRAINT application_history_status_changed CHECK (from_status IS DISTINCT FROM to_status);

-- The application card renders the whole trail newest first.
CREATE INDEX application_history_by_application
    ON app.application_status_history (application_id, occurred_at DESC);


-- ---------------------------------------------------------------------------
-- app.application_document
-- ---------------------------------------------------------------------------

-- Attachments required by scenario C3 step 9: veterinary certificate, proof of
-- a benefit category, power of attorney and so on. The file itself lives in
-- object storage; the row keeps the key, the hash and who checked it.
CREATE TABLE app.application_document (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES app.application,
    doc_type       text NOT NULL,           -- classifier code from nsi, not a CHECK list: the classifier is extensible
    file_name      text NOT NULL,           -- name as uploaded, shown to the user
    storage_key    text NOT NULL UNIQUE,    -- object key in MinIO
    mime_type      text NOT NULL,
    size_bytes     bigint NOT NULL,
    sha256         text NOT NULL,           -- integrity proof, reused by the archive module
    verified_at    timestamptz,
    verified_by    uuid REFERENCES iam.user_account,
    note           text,
    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     uuid,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     uuid
);

ALTER TABLE app.application_document
    ADD CONSTRAINT application_document_size_positive CHECK (size_bytes > 0),
    ADD CONSTRAINT application_document_sha256_format CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    ADD CONSTRAINT application_document_verified_pair CHECK (
        (verified_at IS NULL) = (verified_by IS NULL)
    );

CREATE INDEX application_document_by_application
    ON app.application_document (application_id, doc_type);


-- ---------------------------------------------------------------------------
-- app.calculation
-- ---------------------------------------------------------------------------

-- Reproducibility of the calculation, clause 4.2.15: the same input yields the
-- same result, and any past calculation can be explained after the fact.
-- Column set verbatim from architecture/database.md section 5.
CREATE TABLE app.calculation (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id  uuid NOT NULL REFERENCES app.application,
    norm_id         uuid REFERENCES rules.norm,    -- norm actually applied; NULL for legacy rows
    tariff_id       uuid REFERENCES rules.tariff,  -- tariff actually applied; NULL for legacy rows
    rule_version    text NOT NULL,          -- norm and tariff version at calculation time
    input_snapshot  jsonb NOT NULL,         -- every input the calculation was fed
    max_sb          numeric(12,2) NOT NULL,
    active_permits_sb numeric(12,2) NOT NULL,
    remaining_sb    numeric(12,2) NOT NULL,
    used_sb         numeric(12,2) NOT NULL,
    amount          numeric(18,2) NOT NULL,
    bhm_value       numeric(18,2) NOT NULL, -- base unit value at calculation time
    is_legacy       boolean NOT NULL DEFAULT false,   -- migrated from the legacy system, must not be recalculated
    created_at      timestamptz NOT NULL DEFAULT now(),
    created_by      uuid,
    updated_at      timestamptz NOT NULL DEFAULT now(),
    updated_by      uuid
);

-- Money is numeric(18,2) and nothing else. The legacy system rounded through
-- int() and lost tiyin on every calculation.
ALTER TABLE app.calculation
    ADD CONSTRAINT calculation_amount_non_negative CHECK (amount >= 0),
    ADD CONSTRAINT calculation_bhm_positive CHECK (bhm_value > 0),
    ADD CONSTRAINT calculation_load_non_negative CHECK (
        max_sb >= 0 AND active_permits_sb >= 0 AND used_sb >= 0
    ),
    -- A calculation carries its own inputs, so a norm published later never
    -- changes it. Rows migrated from the legacy system have no traceable
    -- inputs at all, which is exactly what is_legacy marks.
    ADD CONSTRAINT calculation_snapshot_is_object CHECK (jsonb_typeof(input_snapshot) = 'object'),
    ADD CONSTRAINT calculation_legacy_has_no_rules CHECK (
        NOT is_legacy OR (norm_id IS NULL AND tariff_id IS NULL)
    );

-- Recalculation before submission appends a row rather than overwriting, so
-- the current calculation is the newest one.
CREATE INDEX calculation_by_application
    ON app.calculation (application_id, created_at DESC);


-- ---------------------------------------------------------------------------
-- app.contract
-- ---------------------------------------------------------------------------

-- Provisional. Module 10.4 and scenario C7 are missing from the specification
-- entirely, and the contract entity appears in appendix 7 only as a link
-- target of permit and signature - it is never defined. These are open
-- questions P1, P2 and P5 to the customer.
--
-- The table exists because the application state machine already routes
-- through CONTRACT_DRAFT and permit will need a foreign key here. The column
-- set is deliberately the minimum that cannot be wrong, and WILL be revised
-- once P1 and P5 are answered: the parties, the subject, the term, the
-- payment schedule and the signature workflow are all still unknown.
CREATE TABLE app.contract (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id uuid NOT NULL REFERENCES app.application,
    number         text NOT NULL UNIQUE,
    status         text NOT NULL,
    signed_at      timestamptz,
    created_at     timestamptz NOT NULL DEFAULT now(),
    created_by     uuid,
    updated_at     timestamptz NOT NULL DEFAULT now(),
    updated_by     uuid
);

ALTER TABLE app.contract
    -- Provisional list: the contract state machine is not specified anywhere.
    ADD CONSTRAINT contract_status_known CHECK (status IN ('DRAFT','SIGNED','TERMINATED')),
    ADD CONSTRAINT contract_signed_at_required CHECK (status <> 'SIGNED' OR signed_at IS NOT NULL);

CREATE INDEX contract_by_application ON app.contract (application_id);
